### ISSUE TITLE
Allow crate documentation to be rebuilt / rebuild documentation built with bad nightlies

### ISSUE THREAD

**Issue by iliekturtles** [rust-lang/docs.rs#295] opened 2019-02-13 01:52 UTC
Sometimes the nightly version used by docs.rs has defects and generates documentation with issues (see #190 or go to https://docs.rs/uom/0.21.0/src/uom/storage_types.rs.html#7 which gives a JavaScript error `ReferenceError: sourcesIndex is not defined`). Although both issues have been fixed by the current nightly version used by docs.rs, documentation built with the old versions is still being used. It would be nice to allow crate authors to opt-in to having documentation re-built with the currently nightly version or to automatically re-build documentation built with now-known bad nightly versions.

As far as I could find the only way to update documentation currently is to release a new version of the crate to crates.io. This will generate updated documentation for the latest version but leaves old crate versions with the old documentation.

**Comment by QuietMisdreavus** [comment] 2019-02-14 22:30
I would like to support this eventually, but the internal structure of docs.rs makes supporting this problematic right now. We run all doc builds inside a single container, which effectively limits us to building one crate's docs at a time. If we let people re-add their crate to the build queue, that risks crowding out new releases if people request a lot of rebuilds for whatever reason. If, in the future, we can better support concurrent builds, then allowing people to request rebuilds without directly asking @onur or myself (or publishing a new version) would be more feasible.

**Comment by najamelan** [comment] 2019-09-17 18:28
There is also the crates that are published at a time when the build fails because of a bad nightly. It would be nice if failed builds were retried after an update of the compiler.

**Comment by jyn514** [comment] 2019-12-05 03:56
Duplicate of https://github.com/rust-lang/docs.rs/issues/464

**Closed by jyn514** 2019-12-05 03:56 UTC

**Comment by jyn514** [comment] 2019-12-05 03:59
(I know your issue came first, but the other has more activity so I think it makes more sense to link to it)
