### ISSUE TITLE
Font rendering got weird recently

### ISSUE THREAD

**Issue by benesch** [rust-lang/docs.rs#945] opened 2020-08-07 21:59 UTC
docs.rs suddenly started rendering monospace fonts quite differently.

Here's the before:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/882976/89691710-9fdf4800-d8d7-11ea-9ed5-f0dd8e210c65.png">

And here's the after:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/882976/89691629-67d80500-d8d7-11ea-8a5b-435d1722a564.png">

Was this intentional? The only obviously glitch is the `fi` ligature (which is _weird_ for a monospace font; wonder why that's happening), but as a matter of personal preference I also preferred the smaller and lighter weight fonts in the before screenshot.

**Comment by jyn514** [comment] 2020-08-07 22:04
https://docs.rs/protobuf/2.16.2/protobuf/descriptor/struct.FileDescriptorSet.html

This is probably fallout from #930, it's not an intentional change. According to devtools this is using `font-face: monospace,monospace` so your default monospace font is mostly to blame, but it's still a bug on our end - we should be using rustdoc fonts.

**Comment by jyn514** [comment] 2020-08-07 22:06
I expect this is the same root cause as https://github.com/rust-lang/docs.rs/issues/935

**Comment by jyn514** [comment] 2020-08-07 22:11
Actually I think this is #937, the pure-css files are being loaded where they weren't before. Let me try reverting those locally and see if it helps.

**Comment by jyn514** [comment] 2020-08-07 23:20
Fixed by #946

**Closed by jyn514** 2020-08-07 23:20 UTC
Labels: A-frontend, C-bug, P-medium

**Comment by benesch** [comment] 2020-08-08 03:44
Ah yep, that fixed it right up. Thanks very much for the quick fix!
