### ISSUE TITLE
Can't type the letter "s"

### ISSUE THREAD

**Issue by ajgajg1134** [rust-lang/docs.rs#190] opened 2018-03-28 19:46 UTC
If you go to a docs.rs page, click into the search box the letter "s" doesn't type. (I assume this has something to do with the way "S" is used as a shortcut for search. (Sometimes it just works, I haven't found the pattern, but this page is an example of it not working: https://docs.rs/yup-oauth2/1.0.7/yup_oauth2/?search=)

Tested on Firefox and Chrome on two different Windows machines.

**Comment by onur** [comment] 2018-03-28 20:26
Hi @ajgajg1134, thanks for reporting.

rustc used in docs.rs have this issue and I believe @GuillaumeGomez fixed this issue last week (https://github.com/rust-lang/rust/pull/49152). Updating nightly in docs.rs should fix this issue.

**Comment by GuillaumeGomez** [comment] 2018-03-28 20:49
I confirm it has been fixed.

**Comment by ivanovaleksey** [comment] 2018-04-19 12:41
According to [this](https://github.com/rust-lang/rust/issues/50074#issuecomment-382716958) comment some upgrades should be done

**Comment by CAD97** [comment] 2018-04-21 02:27
For people dealing with the issue: The search results page doesn't have the issue, so typing anything that isn't an `s` then waiting will allow you to type `s`s.

I can confirm that a crate released 4 hours ago's documentation on docs.rs still has this issue, so we're waiting somewhat patiently for a rustdoc update in the docs.rs pipeline (and then a rebuild for every crate's documentation that got built by the bad rustdoc...)

**Comment by ivanovaleksey** [comment] 2018-04-21 07:05
@CAD97 is rebuilding everything is possible? I believe just fixing the issue would be enough. 
Crates documentation would be updated on new releases.

**Comment by CAD97** [comment] 2018-04-21 20:37
@ivanovaleksey Yeah, just updating rustdoc will fix it for new releases, but that also means that any crate that got hit by the issue would have to notice that they did and release a new minor version just to fix the docs.

Either way, for the issue to not happen on any of docs.rs' documentation, the user has to wait for a new build of the documentation, whether that's because all bad documentation was rebuilt automatically or the crate owner pushed a new version (and even then, the old version's documentation is still available).

**Comment by sinesc** [comment] 2018-05-12 09:07
This also happens with "-" which expands/closes description blocks.

**Comment by z2oh** [comment] 2018-09-25 16:50
Is rebuilding the docs for old crates a possibility? There are lots of crates that still haven't had an update since this bug was fixed.

**Comment by jyn514** [comment] 2019-12-07 15:55
@z2oh rebuilding automagically is #464 

(also, hi Jeremy :laughing:)

**Comment by jyn514** [comment] 2019-12-07 16:11
Both 's' and '-' are fixed on the latest version.

**Closed by jyn514** 2019-12-07 16:11 UTC
