### ISSUE TITLE
API for programmatic documentation fetching

### ISSUE THREAD

**Issue by ghost** [rust-lang/docs.rs#88] opened 2016-12-17 13:52 UTC

**Comment by conradev** [comment] 2017-03-02 03:43
I would love to see this as well. If there was a way to download an archive of the raw HTML of the documentation, that would be fantastic.

My goal is to hook `docs.rs` up to [Dash](https://kapeli.com/dash)

**Comment by xusss** [comment] 2017-05-09 10:10
@conradev How is the progress? :)

**Comment by jyn514** [comment] 2020-01-09 13:56
Duplicate of https://github.com/rust-lang/docs.rs/issues/174

**Closed by jyn514** 2020-01-09 13:56 UTC
