### ISSUE TITLE
Mobile: Opening rustdoc hamburger menu overlaps rustdoc header

### ISSUE THREAD

**Issue by jsha** [rust-lang/docs.rs#1121] opened 2020-10-24 22:34 UTC
Steps to reproduce:

1. On a mobile device (or in Chrome's mobile simulation mode), visit a crate page, for instance https://docs.rs/ureq/1.5.1/ureq/index.html.
2. Tap the hamburger menu in the top left.

Expected result:

Rustdoc's crate header is not obscured by the menu.

Actual result:

The header is obscured by the menu.

https://docs.rs/ureq/1.5.1/ureq/index.html

![image](https://user-images.githubusercontent.com/220205/97094893-27eb0900-160e-11eb-861c-ea5d72d05569.png)

vs https://doc.rust-lang.org/std/vec/struct.Vec.html

![image](https://user-images.githubusercontent.com/220205/97094914-51a43000-160e-11eb-905f-f4ff93ddec62.png)

(noticed while writing up #1120 )

**Comment by arusahni** [comment] 2020-12-31 03:42
I've confirmed this problem still exists. Would it be an issue if I picked it up? The immediate fix (adjusting the `top` offset to use the correct math) seems fairly straightforward. However, there's some additional jank around opening the sidebar that causes the Rust logo and crate name to shift on open and close. Since I'd already be poking around in that element, I can investigate and fix that, too.

I'll take care to not go overboard as #1120 proposes something that could make this component not long for the world.

**Comment by jyn514** [comment] 2020-12-31 17:08
@arusahni go for it :) this seems to be a docs.rs specific bug, so I'd start by finding why this is different from normal docs that rustdoc generates.

**Comment by arusahni** [comment] 2020-12-31 23:07
@jyn514 after some comparison, it boils down to it being because of the docs.rs shell. The sidebar is a `fixed` position element, with its `top` offset being 45px from the top. With rustdoc's output, that magic number is the height of the topbar. However this number is different for docs.rs due to the navbar - it's instead 45px + 32px (where the latter is the height of the docs.rs navbar).

**Comment by arusahni** [comment] 2021-01-01 15:51
These (and some Clippy warnings) are addressed in PR #1233.

**Closed** 2021-01-01 18:50 UTC
Labels: A-rustdoc-css, C-bug
