### ISSUE TITLE
Building documentation fails with "expected value" error

### ISSUE THREAD

**Issue by Kogia-sima** [rust-lang/docs.rs#818] opened 2020-06-06 11:37 UTC
**Crate name:** sailfish
**Build failure link:** (no build logs)

**Additional details:**

Yesterday I published [sailfish](https://crates.io/crates/sailfish) crate, but no links to docs.rs appears.

However, for [sailfish-macros](https://crates.io/crates/sailfish-macros) crate the documentation exists.

I tried to check the [build log](https://docs.rs/crate/sailfish/0.0.2/builds) but I can't find any logs.

Also I cloned this repository and executed the following command:

```console
$ docker-compose run web build crate sailfish 0.0.2
```

However, that command failed with the that error:

```
thread 'main' panicked at 'Building documentation failed: Error("expected value", line: 1, column: 1)', src/bin/cratesfyi.rs:321:21
```

<details><summary>Full outputs:</summary>
<p>

```
$ docker-compose run web build crate sailfish 0.0.2
Starting docsrs_s3_1 ... done
Starting docsrs_db_1 ... done

export CRATESFYI_PREFIX=/opt/docsrs/prefix
export DOCS_RS_DOCKER=true
export RUST_LOG=${RUST_LOG-cratesfyi,rustwide=info}
export PATH="$PATH:/build/target/release"

# Try migrating the database multiple times if it fails
# This avoids the docker container crashing the first time it's started with
# docker-compose, as PostgreSQL needs some time to initialize.
set +e
failed=0
while true; do
    if ! cratesfyi database migrate; then
        ((failed=failed + 1))
        if [ "${failed}" -eq 5 ]; then
            exit 1
        fi
        echo "failed to migrate the database"
        echo "waiting 1 second..."
        sleep 1
    else
        break
    fi
done
set -e

cratesfyi database update-release-activity

if ! [ -d "${CRATESFYI_PREFIX}/crates.io-index/.git" ]; then
    git clone https://github.com/rust-lang/crates.io-index "${CRATESFYI_PREFIX}/crates.io-index"
    # Prevent new crates built before the container creation to be built
    git --git-dir="$CRATESFYI_PREFIX/crates.io-index/.git" branch crates-index-diff_last-seen
fi

cratesfyi build update-toolchain --only-first-time
update-toolchain was already called in the past, exiting

cratesfyi "$@"
2020/06/06 11:27:32 [DEBUG] cratesfyi::docbuilder: Loading cache
2020/06/06 11:27:32 [DEBUG] cratesfyi::docbuilder: Loading database cache
2020/06/06 11:27:32 [INFO] rustwide::cmd::sandbox: pulling image rustops/crates-build-env from Docker Hub
2020/06/06 11:27:32 [INFO] rustwide::cmd: running `Command { std: "docker" "pull" "rustops/crates-build-env", kill_on_drop: false }`
2020/06/06 11:27:32 [INFO] rustwide::cmd: [stdout] Using default tag: latest
2020/06/06 11:27:35 [INFO] rustwide::cmd: [stdout] latest: Pulling from rustops/crates-build-env
2020/06/06 11:27:35 [INFO] rustwide::cmd: [stdout] Digest: sha256:034db2cf6407dfaf51ec4b73cd2c81d48ed5f54fc72883dd620192adbdc8ff3c
2020/06/06 11:27:35 [INFO] rustwide::cmd: [stdout] Status: Image is up to date for rustops/crates-build-env:latest
2020/06/06 11:27:35 [INFO] rustwide::cmd: [stdout] docker.io/rustops/crates-build-env:latest
2020/06/06 11:27:35 [INFO] rustwide::cmd::sandbox: checking the image rustops/crates-build-env is available locally
2020/06/06 11:27:35 [INFO] rustwide::cmd: running `Command { std: "docker" "image" "inspect" "rustops/crates-build-env", kill_on_drop: false }`
2020/06/06 11:27:35 [INFO] rustwide::inside_docker: detecting the ID of the container where rustwide is running
2020/06/06 11:27:35 [INFO] rustwide::inside_docker: probing container id 9b975b7b7f11f02cb6a95c9ea74e4e1c6143107bd3fcd7777dd34b7ac5637e28
2020/06/06 11:27:36 [INFO] rustwide::inside_docker: probe successful, this is container ID 9b975b7b7f11f02cb6a95c9ea74e4e1c6143107bd3fcd7777dd34b7ac5637e28
2020/06/06 11:27:36 [INFO] rustwide::inside_docker: inspecting the current container
2020/06/06 11:27:36 [INFO] rustwide::workspace: installing tools required by rustwide
2020/06/06 11:27:36 [INFO] rustwide::tools: tool rustup is installed, trying to update it
2020/06/06 11:27:36 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/rustup" "self" "update", kill_on_drop: false }`
2020/06/06 11:27:36 [INFO] rustwide::cmd: [stderr] info: checking for self-updates
2020/06/06 11:27:36 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/rustup" "update" "stable", kill_on_drop: false }`
2020/06/06 11:27:36 [INFO] rustwide::cmd: [stderr] info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
2020/06/06 11:27:36 [INFO] rustwide::cmd: [stdout]
2020/06/06 11:27:36 [INFO] rustwide::cmd: [stdout]   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.44.0 (49cae5576 2020-06-01)
2020/06/06 11:27:36 [INFO] rustwide::cmd: [stdout]
2020/06/06 11:27:36 [INFO] rustwide::cmd: [stderr] info: checking for self-updates
2020/06/06 11:27:36 [INFO] rustwide::tools: tool rustup-toolchain-install-master is installed, trying to update it
2020/06/06 11:27:36 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+stable" "install" "rustup-toolchain-install-master", kill_on_drop: false }`
2020/06/06 11:27:36 [INFO] rustwide::cmd: [stderr]     Updating crates.io index
2020/06/06 11:27:37 [INFO] rustwide::cmd: [stderr]      Ignored package `rustup-toolchain-install-master v1.7.3` is already installed, use --force to override
2020/06/06 11:27:37 [INFO] rustwide::tools: tool git-credential-null is installed, trying to update it
2020/06/06 11:27:37 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+stable" "install" "git-credential-null", kill_on_drop: false }`
2020/06/06 11:27:37 [INFO] rustwide::cmd: [stderr]     Updating crates.io index
2020/06/06 11:27:37 [INFO] rustwide::cmd: [stderr]      Ignored package `git-credential-null v1.0.1` is already installed, use --force to override
2020/06/06 11:27:37 [INFO] cratesfyi::docbuilder::rustwide_builder: detecting rustc's version...
2020/06/06 11:27:37 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/rustc" "+nightly" "--version", kill_on_drop: false }`
2020/06/06 11:27:37 [INFO] cratesfyi::docbuilder::rustwide_builder: found rustc rustc 1.46.0-nightly (826cb062a 2020-06-05)
2020/06/06 11:27:37 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/rustup" "target" "list" "--installed" "--toolchain" "nightly", kill_on_drop: false }`
2020/06/06 11:27:37 [INFO] rustwide::toolchain: installing toolchain nightly
2020/06/06 11:27:37 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/rustup" "toolchain" "install" "nightly" "--profile" "minimal", kill_on_drop: false }`
2020/06/06 11:27:37 [INFO] rustwide::cmd: [stderr] info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
2020/06/06 11:27:38 [INFO] rustwide::cmd: [stdout]
2020/06/06 11:27:38 [INFO] rustwide::cmd: [stdout]   nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.46.0-nightly (826cb062a 2020-06-05)
2020/06/06 11:27:38 [INFO] rustwide::cmd: [stdout]
2020/06/06 11:27:38 [INFO] rustwide::cmd: [stderr] info: checking for self-updates
2020/06/06 11:27:38 [INFO] cratesfyi::docbuilder::rustwide_builder: detecting rustc's version...
2020/06/06 11:27:38 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/rustc" "+nightly" "--version", kill_on_drop: false }`
2020/06/06 11:27:38 [INFO] cratesfyi::docbuilder::rustwide_builder: found rustc rustc 1.46.0-nightly (826cb062a 2020-06-05)
2020/06/06 11:27:38 [INFO] cratesfyi::docbuilder::rustwide_builder: building package sailfish 0.0.2
2020/06/06 11:27:38 [INFO] rustwide::crates::cratesio: fetching crate sailfish 0.0.2...
2020/06/06 11:27:38 [INFO] rustwide::crates::cratesio: extracting crate sailfish 0.0.2 into /opt/docsrs/rustwide/builds/sailfish-0.0.2/source
2020/06/06 11:27:38 [INFO] rustwide::prepare: validating manifest of crates.io crate sailfish 0.0.2 on toolchain nightly
2020/06/06 11:27:38 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "read-manifest" "--manifest-path" "Cargo.toml", kill_on_drop: false }`
2020/06/06 11:27:38 [INFO] rustwide::prepare: started tweaking crates.io crate sailfish 0.0.2
2020/06/06 11:27:38 [INFO] rustwide::prepare: finished tweaking crates.io crate sailfish 0.0.2
2020/06/06 11:27:38 [INFO] rustwide::prepare: tweaked toml for crates.io crate sailfish 0.0.2 written to /opt/docsrs/rustwide/builds/sailfish-0.0.2/source/Cargo.toml
2020/06/06 11:27:38 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "generate-lockfile" "--manifest-path" "Cargo.toml", kill_on_drop: false }`
2020/06/06 11:27:38 [INFO] rustwide::cmd: [stderr]     Updating crates.io index
2020/06/06 11:27:38 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "fetch" "--locked" "--manifest-path" "Cargo.toml", kill_on_drop: false }`
2020/06/06 11:27:38 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
2020/06/06 11:27:39 [INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/target:/opt/rustwide/target:rw,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=0" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200605-1.46.0-nightly-826cb062a --static-root-path / --cap-lints warn --extern-html-root-url ryu=https://docs.rs/ryu/1.0.5 --extern-html-root-url itoa=https://docs.rs/itoa/0.4.5" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps", kill_on_drop: false }`
2020/06/06 11:27:39 [INFO] rustwide::cmd: [stdout] cf0c3db99156995be8d77017e9285016cd3c201b30c27dd26a59b037972d3a50
2020/06/06 11:27:39 [INFO] rustwide::cmd: [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2020/06/06 11:27:39 [INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "cf0c3db99156995be8d77017e9285016cd3c201b30c27dd26a59b037972d3a50", kill_on_drop: false }`
2020/06/06 11:27:40 [INFO] rustwide::cmd: [stderr] sudo: setrlimit(RLIMIT_CORE): Operation not permitted
2020/06/06 11:27:40 [INFO] rustwide::cmd: [stderr]    Compiling ryu v1.0.5
2020/06/06 11:27:40 [INFO] rustwide::cmd: [stderr]     Checking itoa v0.4.5
2020/06/06 11:27:40 [INFO] rustwide::cmd: [stderr]  Documenting sailfish v0.0.2 (/opt/rustwide/workdir)
2020/06/06 11:27:42 [INFO] rustwide::cmd: [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 2.42s
2020/06/06 11:27:42 [INFO] rustwide::cmd: running `Command { std: "docker" "inspect" "cf0c3db99156995be8d77017e9285016cd3c201b30c27dd26a59b037972d3a50", kill_on_drop: false }`
2020/06/06 11:27:42 [INFO] rustwide::cmd: running `Command { std: "docker" "rm" "-f" "cf0c3db99156995be8d77017e9285016cd3c201b30c27dd26a59b037972d3a50", kill_on_drop: false }`
2020/06/06 11:27:42 [INFO] rustwide::cmd: [stdout] cf0c3db99156995be8d77017e9285016cd3c201b30c27dd26a59b037972d3a50
2020/06/06 11:27:42 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding sources into database
2020/06/06 11:27:42 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding documentation for the default target to the database
2020/06/06 11:27:42 [INFO] cratesfyi::docbuilder::rustwide_builder: /opt/docsrs/rustwide/builds/sailfish-0.0.2/target/doc /tmp/docsrs-docsNn6XqZ
2020/06/06 11:27:42 [DEBUG] cratesfyi::docbuilder::rustwide_builder: building package sailfish 0.0.2 for i686-unknown-linux-gnu
2020/06/06 11:27:42 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
2020/06/06 11:27:43 [INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/target:/opt/rustwide/target:rw,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=0" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200605-1.46.0-nightly-826cb062a --static-root-path / --cap-lints warn --extern-html-root-url itoa=https://docs.rs/itoa/0.4.5 --extern-html-root-url ryu=https://docs.rs/ryu/1.0.5" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps" "--target" "i686-unknown-linux-gnu", kill_on_drop: false }`
2020/06/06 11:27:43 [INFO] rustwide::cmd: [stdout] d8b0fa60ac57af37f060ff378d96744a56c9e678807705d905df872a6f86a692
2020/06/06 11:27:43 [INFO] rustwide::cmd: [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2020/06/06 11:27:43 [INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "d8b0fa60ac57af37f060ff378d96744a56c9e678807705d905df872a6f86a692", kill_on_drop: false }`
2020/06/06 11:27:44 [INFO] rustwide::cmd: [stderr] sudo: setrlimit(RLIMIT_CORE): Operation not permitted
2020/06/06 11:27:44 [INFO] rustwide::cmd: [stderr]     Checking itoa v0.4.5
2020/06/06 11:27:44 [INFO] rustwide::cmd: [stderr]    Compiling ryu v1.0.5
2020/06/06 11:27:44 [INFO] rustwide::cmd: [stderr]  Documenting sailfish v0.0.2 (/opt/rustwide/workdir)
2020/06/06 11:27:45 [INFO] rustwide::cmd: [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 1.84s
2020/06/06 11:27:46 [INFO] rustwide::cmd: running `Command { std: "docker" "inspect" "d8b0fa60ac57af37f060ff378d96744a56c9e678807705d905df872a6f86a692", kill_on_drop: false }`
2020/06/06 11:27:46 [INFO] rustwide::cmd: running `Command { std: "docker" "rm" "-f" "d8b0fa60ac57af37f060ff378d96744a56c9e678807705d905df872a6f86a692", kill_on_drop: false }`
2020/06/06 11:27:46 [INFO] rustwide::cmd: [stdout] d8b0fa60ac57af37f060ff378d96744a56c9e678807705d905df872a6f86a692
2020/06/06 11:27:46 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding documentation for target i686-unknown-linux-gnu to the database
2020/06/06 11:27:46 [INFO] cratesfyi::docbuilder::rustwide_builder: /opt/docsrs/rustwide/builds/sailfish-0.0.2/target/i686-unknown-linux-gnu/doc /tmp/docsrs-docsNn6XqZ/i686-unknown-linux-gnu
2020/06/06 11:27:46 [DEBUG] cratesfyi::docbuilder::rustwide_builder: building package sailfish 0.0.2 for x86_64-apple-darwin
2020/06/06 11:27:46 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
2020/06/06 11:27:46 [INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/target:/opt/rustwide/target:rw,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=0" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200605-1.46.0-nightly-826cb062a --static-root-path / --cap-lints warn --extern-html-root-url itoa=https://docs.rs/itoa/0.4.5 --extern-html-root-url ryu=https://docs.rs/ryu/1.0.5" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps" "--target" "x86_64-apple-darwin", kill_on_drop: false }`
2020/06/06 11:27:46 [INFO] rustwide::cmd: [stdout] 008b62d9720a9e6b0048aa3ab6b5ed4005a919cfae325735a14fa5bcd509ae94
2020/06/06 11:27:46 [INFO] rustwide::cmd: [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2020/06/06 11:27:46 [INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "008b62d9720a9e6b0048aa3ab6b5ed4005a919cfae325735a14fa5bcd509ae94", kill_on_drop: false }`
2020/06/06 11:27:47 [INFO] rustwide::cmd: [stderr] sudo: setrlimit(RLIMIT_CORE): Operation not permitted
2020/06/06 11:27:47 [INFO] rustwide::cmd: [stderr]     Checking itoa v0.4.5
2020/06/06 11:27:47 [INFO] rustwide::cmd: [stderr]    Compiling ryu v1.0.5
2020/06/06 11:27:47 [INFO] rustwide::cmd: [stderr]  Documenting sailfish v0.0.2 (/opt/rustwide/workdir)
2020/06/06 11:27:49 [INFO] rustwide::cmd: [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 1.82s
2020/06/06 11:27:49 [INFO] rustwide::cmd: running `Command { std: "docker" "inspect" "008b62d9720a9e6b0048aa3ab6b5ed4005a919cfae325735a14fa5bcd509ae94", kill_on_drop: false }`
2020/06/06 11:27:49 [INFO] rustwide::cmd: running `Command { std: "docker" "rm" "-f" "008b62d9720a9e6b0048aa3ab6b5ed4005a919cfae325735a14fa5bcd509ae94", kill_on_drop: false }`
2020/06/06 11:27:49 [INFO] rustwide::cmd: [stdout] 008b62d9720a9e6b0048aa3ab6b5ed4005a919cfae325735a14fa5bcd509ae94
2020/06/06 11:27:49 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding documentation for target x86_64-apple-darwin to the database
2020/06/06 11:27:49 [INFO] cratesfyi::docbuilder::rustwide_builder: /opt/docsrs/rustwide/builds/sailfish-0.0.2/target/x86_64-apple-darwin/doc /tmp/docsrs-docsNn6XqZ/x86_64-apple-darwin
2020/06/06 11:27:49 [DEBUG] cratesfyi::docbuilder::rustwide_builder: building package sailfish 0.0.2 for x86_64-pc-windows-msvc
2020/06/06 11:27:49 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
2020/06/06 11:27:49 [INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/target:/opt/rustwide/target:rw,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=0" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200605-1.46.0-nightly-826cb062a --static-root-path / --cap-lints warn --extern-html-root-url itoa=https://docs.rs/itoa/0.4.5 --extern-html-root-url ryu=https://docs.rs/ryu/1.0.5" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps" "--target" "x86_64-pc-windows-msvc", kill_on_drop: false }`
2020/06/06 11:27:50 [INFO] rustwide::cmd: [stdout] 4fa0278b89df84cbf76ecc7c970dcbe7d16e5279aa491b883aad7acf4bb03c1c
2020/06/06 11:27:50 [INFO] rustwide::cmd: [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2020/06/06 11:27:50 [INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "4fa0278b89df84cbf76ecc7c970dcbe7d16e5279aa491b883aad7acf4bb03c1c", kill_on_drop: false }`
2020/06/06 11:27:50 [INFO] rustwide::cmd: [stderr] sudo: setrlimit(RLIMIT_CORE): Operation not permitted
2020/06/06 11:27:50 [INFO] rustwide::cmd: [stderr]     Checking itoa v0.4.5
2020/06/06 11:27:50 [INFO] rustwide::cmd: [stderr]    Compiling ryu v1.0.5
2020/06/06 11:27:51 [INFO] rustwide::cmd: [stderr]  Documenting sailfish v0.0.2 (/opt/rustwide/workdir)
2020/06/06 11:27:52 [INFO] rustwide::cmd: [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 1.79s
2020/06/06 11:27:52 [INFO] rustwide::cmd: running `Command { std: "docker" "inspect" "4fa0278b89df84cbf76ecc7c970dcbe7d16e5279aa491b883aad7acf4bb03c1c", kill_on_drop: false }`
2020/06/06 11:27:53 [INFO] rustwide::cmd: running `Command { std: "docker" "rm" "-f" "4fa0278b89df84cbf76ecc7c970dcbe7d16e5279aa491b883aad7acf4bb03c1c", kill_on_drop: false }`
2020/06/06 11:27:53 [INFO] rustwide::cmd: [stdout] 4fa0278b89df84cbf76ecc7c970dcbe7d16e5279aa491b883aad7acf4bb03c1c
2020/06/06 11:27:53 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding documentation for target x86_64-pc-windows-msvc to the database
2020/06/06 11:27:53 [INFO] cratesfyi::docbuilder::rustwide_builder: /opt/docsrs/rustwide/builds/sailfish-0.0.2/target/x86_64-pc-windows-msvc/doc /tmp/docsrs-docsNn6XqZ/x86_64-pc-windows-msvc
2020/06/06 11:27:53 [DEBUG] cratesfyi::docbuilder::rustwide_builder: building package sailfish 0.0.2 for i686-pc-windows-msvc
2020/06/06 11:27:53 [INFO] rustwide::cmd: running `Command { std: "/opt/docsrs/rustwide/cargo-home/bin/cargo" "+nightly" "metadata" "--format-version" "1", kill_on_drop: false }`
2020/06/06 11:27:53 [INFO] rustwide::cmd: running `Command { std: "docker" "create" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/target:/opt/rustwide/target:rw,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/builds/sailfish-0.0.2/source:/opt/rustwide/workdir:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/cargo-home:/opt/rustwide/cargo-home:ro,Z" "-v" "/home/kogia-sima/PG/Rust/3rdparty/docs.rs/.rustwide-docker/rustup-home:/opt/rustwide/rustup-home:ro,Z" "-e" "SOURCE_DIR=/opt/rustwide/workdir" "-e" "MAP_USER_ID=0" "-e" "CARGO_TARGET_DIR=/opt/rustwide/target" "-e" "RUSTFLAGS=" "-e" "RUSTDOCFLAGS=-Z unstable-options --resource-suffix -20200605-1.46.0-nightly-826cb062a --static-root-path / --cap-lints warn --extern-html-root-url ryu=https://docs.rs/ryu/1.0.5 --extern-html-root-url itoa=https://docs.rs/itoa/0.4.5" "-e" "CARGO_HOME=/opt/rustwide/cargo-home" "-e" "RUSTUP_HOME=/opt/rustwide/rustup-home" "-w" "/opt/rustwide/workdir" "-m" "3221225472" "--network" "none" "rustops/crates-build-env" "/opt/rustwide/cargo-home/bin/cargo" "+nightly" "doc" "--lib" "--no-deps" "--target" "i686-pc-windows-msvc", kill_on_drop: false }`
2020/06/06 11:27:53 [INFO] rustwide::cmd: [stderr] WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2020/06/06 11:27:53 [INFO] rustwide::cmd: [stdout] c2471c6300ad7874b93af3e47d0088c2955944770b8954cdcfc6c70adaa01c6b
2020/06/06 11:27:53 [INFO] rustwide::cmd: running `Command { std: "docker" "start" "-a" "c2471c6300ad7874b93af3e47d0088c2955944770b8954cdcfc6c70adaa01c6b", kill_on_drop: false }`
2020/06/06 11:27:54 [INFO] rustwide::cmd: [stderr] sudo: setrlimit(RLIMIT_CORE): Operation not permitted
2020/06/06 11:27:54 [INFO] rustwide::cmd: [stderr]     Checking itoa v0.4.5
2020/06/06 11:27:54 [INFO] rustwide::cmd: [stderr]    Compiling ryu v1.0.5
2020/06/06 11:27:54 [INFO] rustwide::cmd: [stderr]  Documenting sailfish v0.0.2 (/opt/rustwide/workdir)
2020/06/06 11:27:56 [INFO] rustwide::cmd: [stderr]     Finished dev [unoptimized + debuginfo] target(s) in 1.76s
2020/06/06 11:27:56 [INFO] rustwide::cmd: running `Command { std: "docker" "inspect" "c2471c6300ad7874b93af3e47d0088c2955944770b8954cdcfc6c70adaa01c6b", kill_on_drop: false }`
2020/06/06 11:27:56 [INFO] rustwide::cmd: running `Command { std: "docker" "rm" "-f" "c2471c6300ad7874b93af3e47d0088c2955944770b8954cdcfc6c70adaa01c6b", kill_on_drop: false }`
2020/06/06 11:27:56 [INFO] rustwide::cmd: [stdout] c2471c6300ad7874b93af3e47d0088c2955944770b8954cdcfc6c70adaa01c6b
2020/06/06 11:27:56 [DEBUG] cratesfyi::docbuilder::rustwide_builder: adding documentation for target i686-pc-windows-msvc to the database
2020/06/06 11:27:56 [INFO] cratesfyi::docbuilder::rustwide_builder: /opt/docsrs/rustwide/builds/sailfish-0.0.2/target/i686-pc-windows-msvc/doc /tmp/docsrs-docsNn6XqZ/i686-pc-windows-msvc
2020/06/06 11:27:56 [DEBUG] cratesfyi::docbuilder::rustwide_builder: Adding documentation into database
thread 'main' panicked at 'Building documentation failed: Error("expected value", line: 1, column: 1)', src/bin/cratesfyi.rs:321:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

</p></details>

**Comment by pietroalbini** [comment] 2020-06-06 11:40
Thanks for reporting this!

There was a bug in docs.rs that caused an outage for builds. [You can see the incident here.](https://status.crates.io/incidents/npxr8t10g7yp) The root cause of the outage is now fixed, and your crate is [in the queue to be built](https://docs.rs/releases/queue). It might take a while for the documentation to appear while the server works through the backlog.

**Closed by pietroalbini** 2020-06-06 11:40 UTC
Labels: build-failure
