### ISSUE TITLE
The documentation generated for recent crates all have missing 404 assets

### ISSUE THREAD

**Issue by mmaroti** [rust-lang/docs.rs#832] opened 2020-06-12 09:15 UTC
Please look at these crates, or anything that was recently built:

https://docs.rs/lightspeed_logger/0.12.2/lightspeed_logger/
https://docs.rs/bc/0.1.8/bc/
https://docs.rs/execute/0.2.4/execute/
https://docs.rs/cadical/0.1.11/cadical/

**Comment by pietroalbini** [comment] 2020-06-12 10:41
On it.

**Comment by pietroalbini** [comment] 2020-06-12 11:18
The current nightly (`nightly-2020-06-12`) has a cargo bug that fails the build if a crate defines a README that doesn't exist in the published crate, even when the README is not actually needed. A PR fixing the bug was merged [on cargo](https://github.com/rust-lang/cargo/pull/8353) and [rustc](https://github.com/rust-lang/rust/pull/73266), so the next nightly will not have the problem.

The bug affected around 60 crates that failed to build since the nightly was released, as well as the crate we use to gather static assets (causing the isssue you encountered).

I pinned the previous nightly (`nightly-2020-06-11`) which is confirmed to work, and re-queued all the crates that failed to build. I'm now in the process of figuring out a way to build assets for the crates built since that nightly was released.

**Comment by pietroalbini** [comment] 2020-06-12 11:29
Generated the shared assets for the crates built since that nightly was released!

Thanks for bringing this issue up! I believe everything is now fixed or queued to be fixed automatically, so I'm going to close the issue. Let us know if you notice any more problems.

**Closed by pietroalbini** 2020-06-12 11:29 UTC
Labels: build-failure

**Comment by mmaroti** [comment] 2020-06-12 14:00
Thanks!
