### ISSUE TITLE
[src] links point to other website

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/docs.rs#298] opened 2019-02-14 12:12 UTC
The `[src]` links on https://docs.rs/futures-preview/0.3.0-alpha.12/futures/stream/struct.Forward.html point to https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.12/futures_util/src/futures_util/stream/forward.rs.html#22-26. This seems likely to be related to the [`#[doc(html_root_url)]`](https://github.com/rust-lang-nursery/futures-rs/blob/ebbc6be1b72b70af33e37f4106a66f8872e8c1cb/futures-util/src/lib.rs#L12) setting in the sub-crate that this type is actually from.

**Comment by QuietMisdreavus** [comment] 2019-02-14 22:12
This is entirely because of the `html_root_url` attribute, though it should be overridden by a `--extern-html-root-url` path that docs.rs is passing to rustdoc. Since [the build log](https://docs.rs/crate/futures-preview/0.3.0-alpha.12/builds/137380) shows that that flag is being passed, i'm going to assume this is an upstream rustdoc problem. I'll try transferring the issue to rust-lang/rust, since that's where rustdoc lives.

**Comment by QuietMisdreavus** [comment] 2019-02-14 22:19
Apparently you need full admin access to use the "Transfer issue" button, so i've just reopened the issue over there as https://github.com/rust-lang/rust/issues/58472. I'll close the issue here since the work all needs to happen upstream.

**Comment by QuietMisdreavus** [comment] 2019-02-18 20:14
Looks like i was mistaken - it's not a bug in upstream rustdoc, but in docs.rs here. To quote @ollie27 in the rust-lang/rust issue:

> The [build log](https://docs.rs/crate/futures-preview/0.3.0-alpha.12/builds/137380) shows rustdoc was passed `--extern-html-root-url 'futures_util_preview=https://docs.rs/futures-util-preview/0.3.0-alpha.12'` but the crate name is `futures_util` not `futures_util_preview`. It looks like docs.rs needs to use the actual crate name not the package name.

**Comment by jyn514** [comment] 2020-02-01 16:17
This may be fixed by https://github.com/rust-lang/rust/issues/67804.

**Comment by jyn514** [comment] 2021-04-17 20:11
This was fixed by https://github.com/rust-lang/docs.rs/pull/1188 (and looking at that PR, looks like this is a duplicate of https://github.com/rust-lang/docs.rs/issues/1166).

**Closed by jyn514** 2021-04-17 20:11 UTC
Labels: A-builds
