### ISSUE TITLE
docs.rs stuck in Chrome and Chromium

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/docs.rs#1975] opened 2022-12-24 08:32 UTC
when scrolling the docs.rs in Chrome or Chromium, the web page is stuck, I need to switch the tab to another one and then switch back to make the web page become normal

F12 console doesn't have any warn or error, and the browser everything looks good except this web page, yes event 1 docs.rs web page is stuck the other one may use normally

**Comment by syphar** [comment] 2022-12-27 09:25
Hi @Sherlock-Holo, 

I can't reproduce this issue in chrome on my machine, I would also assume that if this is a bug for everyone, more users would report it. 

Which exact page are you trying? 

Also, can you try after disabling eventually active extensions?

**Comment by syphar** [comment] 2023-01-11 19:24
I'm closing this since we can't reproduce this and don't get answers. 

Feel free to reopen this issue if it still happens!

**Closed** 2023-01-11 19:24 UTC

**Comment by Sherlock-Holo** [comment] 2023-01-12 01:05
sorry for the delay reply
I try open a new profile Chromium and there is no stuck any more, however when i switch back to the normal profile, it happens again.
I will try to disable the plugin one by one to find out what plugin cause this problem
