### ISSUE TITLE
rustfmt is not installed

### ISSUE THREAD

**Issue by elmurci** [rust-lang/docs.rs#652] opened 2020-03-23 09:07 UTC
**Crate name:**
xpring

**Build failure link:**
https://docs.rs/crate/xpring/0.0.4/builds/232409

**Additional details:**
[INFO] [stderr] out: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "error: \'rustfmt\' is not installed for the toolchain \'nightly-x86_64-unknown-linux-gnu\'\nTo install, run `rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu`\n" }

**Comment by jyn514** [comment] 2020-03-23 12:33
Duplicate of #357. I didn't realize it was as easy as installing it with `rustup`, though, that should be a simple fix. I'll add instructions in the linked issue.

**Closed** 2020-03-23 12:33 UTC
Labels: build-failure
