### ISSUE TITLE
Source viewer sometimes links to `empty_library` in file tree

### ISSUE THREAD

**Issue by cdmistman** [rust-lang/docs.rs#1453] opened 2021-07-21 16:33 UTC
In some crates, the file tree simply links to some empty crate called `empty_library` which contains a single file, `lib.rs`. Clicking on the file results in a 404

Most recent example I've found is [in the source viewer for HashBrown](https://docs.rs/hashbrown/0.11.2/src/hashbrown/map.rs.html) (linking to `map.rs`, although accessing any source file through <https://docs.rs/hashbrown/0.11.2> results in the bad source tree. This has happened for multiple crates (and I can add more links as I find them) but notably might only affect certain versions - for example, the source file tree works when looking at <https://docs.rs/hashbrown/0.11.1>

If this is a rustdoc issue and not docs.rs then I can close this issue and reopen in rust-lang/rust

**Comment by syphar** [comment] 2021-07-21 17:28
Thank you for the report! 
This specific source-viewer and it's file-list are build in docs.rs, so it's definitely an issue with us here. 

That being said, I just ran a clean build of this crate and version locally and the file-list is correct. 

So it seems like a past bug / production issue that could be solved by a rebuild. If it isn't a known issue we could query other releases that share the file-list with empty-library, but aren't it. Though it would be tricky to differentiate between these and other empty libraries.

**Comment by Nemo157** [comment] 2021-07-21 21:27
> This specific source-viewer and it's file-list are build in docs.rs, so it's definitely an issue with us here.

This is the one generated by rustdoc, [the docs.rs one](https://docs.rs/crate/hashbrown/0.11.2/source/src/map.rs) looks fine for this release.

**Comment by jyn514** [comment] 2021-07-21 21:37
Duplicate of https://github.com/rust-lang/docs.rs/issues/1313

**Closed by jyn514** 2021-07-21 21:37 UTC

**Comment by syphar** [comment] 2021-07-22 05:21
damn, confused the two viewers again 😆
