### ISSUE TITLE
Redirect short link to latest "public" crate version by default

### ISSUE THREAD

**Issue by Mazwak** [rust-lang/docs.rs#341] opened 2019-04-30 11:35 UTC
If a crate has a "non public" version (beta, rc, …), the default link points to it.

For example, right now, rust-postgres has 0.15.2 as latest, and 0.16.0-rc1 as test.

http://docs.rs/postgres points to 0.16.0-rc1.
I think it would be better to point to 0.15.2.

Most, if not all, people accessing the default want to read the documentation of the  latest "public" version.

**Comment by jyn514** [comment] 2020-01-10 13:10
Duplicate of #223

**Closed by jyn514** 2020-01-10 13:10 UTC
