### ISSUE TITLE
gstreamer 0.16.7 is missing docs generated by the build script

### ISSUE THREAD

**Issue by bilelmoussaoui** [rust-lang/docs.rs#1359] opened 2021-04-17 14:34 UTC
In some situations such as gtk-rs/gstreamer-rs where the docs can't be shipped with the crate for license reasons, it causes a very very low docs coverage which is often not true.

See https://docs.rs/crate/gstreamer/0.16.7 for example. 

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment] 2021-04-17 14:37
Thanks for opening the issue!

Explanations: it'd require to run the `build.rs` script with the `docs.rs` features provided and that's pretty much it.

**Comment by GuillaumeGomez** [comment] 2021-04-17 14:43
I'll send a fix tomorrow.

**Comment by GuillaumeGomez** [comment] 2021-04-17 14:58
Interestingly enough, we use `prepare_commands` which uses in turn `Metadata::cargo_args`. So normally, the features should be set when running the command. Seems like a bigger issue than expected. :)

**Comment by jyn514** [comment] 2021-04-17 17:44
This is not a docs.rs bug. The issue is that the build script fails to generate the docs (which you can see passing `-vv` to the build script):
```
[gstreamer 0.16.7] Cannot open 'src/toc_serde.rs': Read-only file system (os error 30)
[gstreamer 0.16.7] Cannot open 'src/typefind.rs': Read-only file system (os error 30)
[gstreamer 0.16.7] Cannot open 'src/utils.rs': Read-only file system (os error 30)
[gstreamer 0.16.7] Cannot open 'src/value.rs': Read-only file system (os error 30)
[gstreamer 0.16.7] Cannot open 'src/value_serde.rs': Read-only file system (os error 30)
```
We don't allow writing to the source directory; if you want to generate code, you have to output it to OUT_DIR. I'd suggest also changing `gstreamer-rs-lgpl-docs` to give a hard error if generating docs fails.

**Comment by GuillaumeGomez** [comment] 2021-04-17 21:37
Unfortunately, we update the source code files, so that's not possible to simply write to OUT_DIR. Any way how we could go around that limitation? Because otherwise, the doc generated on docs.rs is really the bare minimum...

**Comment by Nemo157** [comment] 2021-04-17 22:00
Rather than updating the source files in place, you could generate a parallel tree of source files into `OUT_DIR` and `include!` them. Even outside of docs.rs modifying the files inside `~/.cargo/registry/src` is not a good setup, that directory is assumed immutable by a lot of tooling.

**Comment by GuillaumeGomez** [comment] 2021-04-18 14:10
It's not possible either, unless we add `include!` on **all** items which would include empty files all the times unless we fill them. It'd literally kill compilation time. So not an option. :-/

**Comment by jplatte** [comment] 2021-04-19 12:04
The `include!` on all the items would be `cfg`-conditional though, right? And so it would only affect compilation time with that feature turned on?

```rust
#[cfg_attr(feature = "embed-lgpl-docs", doc = include!(concat!(env!("OUT_DIR"), "...")))]
```

(one addition downside is that it makes `embed-lgpl-docs` nightly-only until after https://github.com/rust-lang/rust/pull/83366 makes it into stable, if it's not nightly-only already)

**Comment by GuillaumeGomez** [comment] 2021-04-19 14:29
But that would mean one file for every item. That seems like a horrible idea. Anyway, we decided to simply not generate anything on docs.rs. Makes things simpler on our side. We will provide full documentation on our side.

**Comment by bilelmoussaoui** [comment] 2021-04-19 19:09
I suppose we can close this one?

**Comment by jyn514** [comment] 2021-04-19 19:49
Sure, happy to close this if you're going to handle it on your side.

**Closed by jyn514** 2021-04-19 19:49 UTC
Labels: C-build-failure, S-waiting-on-crate-author
