### ISSUE TITLE
Add support for manually uploading docs

### ISSUE THREAD

**Issue by sdroege** [rust-lang/docs.rs#146] opened 2017-08-17 15:19 UTC
It would be nice to have a way for crate owners to manually upload docs to docs.rs. This would at least be useful for crates that can't compile on the docs.rs system, e.g. because the crate is not for the platform used there or because C libraries are missing.

The latter is my use-case with e.g. https://docs.rs/crate/gstreamer-sys/

**Comment by bradfier** [comment] 2017-10-12 09:31
I would support this, I'm writing Rust bindings for proprietary libraries, where uploading the headers we bind to would probably be a licensing violation. So we can build the docs locally, but pushing the build dependencies anywhere public is a no-go.

**Comment by Javyre** [comment] 2017-12-13 23:36
Any updates on this issue yet?

**Comment by jyn514** [comment] 2020-02-01 16:42
Duplicate of https://github.com/rust-lang/docs.rs/issues/146

**Closed by jyn514** 2020-02-01 16:42 UTC

**Comment by jyn514** [comment] 2021-04-22 17:17
Err sorry, I meant to link to https://github.com/rust-lang/docs.rs/issues/93.
