### ISSUE TITLE
The hosted docs.rs site shows crate source code in a mangled way

### ISSUE THREAD

**Issue by jjpe** [rust-lang/docs.rs#364] opened 2019-06-04 09:49 UTC
When I look at the source code for e.g. [itertools](https://docs.rs/itertools/0.8.0/src/itertools/multipeek_impl.rs.html#10-16) on Firefox, I get a mangled view of the code where any given line number is not at the same vertical offset from the top of the page as the line itself:
![image](https://user-images.githubusercontent.com/1242003/58869475-91d3dd00-86be-11e9-98ab-0ce8663c4ebe.png)

I believe that should be fixed.

**Comment by GuillaumeGomez** [comment] 2019-06-04 09:50
It has been fixed a while ago. I just assume that this crate's documentation is old.

**Comment by QuietMisdreavus** [comment] 2019-06-05 18:51
Duplicate of https://github.com/rust-lang/docs.rs/issues/280

I've queued up a rebuild of itertools's docs. Since we don't eagerly rebuild documentation from prior rustc versions, bugs like these stick around

**Closed by QuietMisdreavus** 2019-06-05 18:51 UTC
