### ISSUE TITLE
MSP430 doesn't have libstd or libcore provided upstream

### ISSUE THREAD

**Issue by cr1901** [rust-lang/docs.rs#1683] opened 2022-02-20 01:55 UTC
### Crate name

msp430-rt

### Build failure link

https://docs.rs/crate/msp430-rt/0.3.1/builds/512492

### Additional details

`msp430-none-elf` doesn't have a standard library provided by `nightly`. It _must_ be built as part of the application for now. I figured [these fields](https://github.com/rust-embedded/msp430-rt/blob/master/Cargo.toml#L27-L30) would be enough, but if there's no way to prevent `docs.rs` from trying to download the standard lib, then I can [no longer](https://docs.rs/crate/msp430-rt/0.2.4) build documentation for `msp430-rt`. The current metadata fields don't seem to have a way to tell `rustup` "don't download std".

Some msp430 crates work around needing to compile docs for the `msp430` target by just compiling for the defaults anyway, but due to at least `abi_msp430_interrupt`, this approach doesn't work here (and I don't think it'll work once target-specific calling conventions [are stabilized](https://github.com/rust-lang/rust/issues/38487#issuecomment-1022518853) either).

**Comment by jyn514** [comment] 2022-02-20 04:26
Duplicate of https://github.com/rust-lang/docs.rs/issues/1561

**Closed by jyn514** 2022-02-20 04:26 UTC
