### ISSUE TITLE
Rendering messed up for old crates

### ISSUE THREAD

**Issue by xd009642** [rust-lang/docs.rs#1027] opened 2020-09-02 20:24 UTC
https://docs.rs/syntex_syntax/0.54.0/syntex_syntax/ast/enum.MetaItemKind.html 

So on google chrome Version 84.0.4147.125 (Official Build) (64-bit) using fedora 31 I saw this:

![Screenshot from 2020-09-02 21-23-21](https://user-images.githubusercontent.com/3472518/92032808-9922e400-ed62-11ea-9f55-a9b1a617b100.png)

I know syntex_syntax is deprecated and people should use syn instead, but I guess it would be nice if legacy things rendered properly for future instances where someone will be maintaining legacy software

**Comment by jyn514** [comment] 2020-09-02 20:27
There are two `div`s that both have the `container-rustdoc` class: one underneath `nav-container` and one at the top level of the body. The first one is wrong.
![container-rustdoc](https://user-images.githubusercontent.com/23638587/92033146-30734180-ed39-11ea-9b43-0f3f4a838eb9.png)

Possibly fallout from #930?

**Comment by jyn514** [comment] 2020-09-02 20:30
Relevant code: https://github.com/rust-lang/docs.rs/blob/b93e53f23d15c45b9645dfc1372dd5d7d93678f6/src/utils/html.rs#L33-L49

**Comment by jyn514** [comment] 2020-09-02 20:32
We're adding it in two places 🤦 https://github.com/rust-lang/docs.rs/blob/b93e53f23d15c45b9645dfc1372dd5d7d93678f6/templates/rustdoc/header.html#L7

**Comment by jyn514** [comment] 2020-09-02 20:57
`syntext_syntax` doesn't build with 1.48 so I'm having trouble confirming whether my fix actually works.

**Comment by jyn514** [comment] 2020-09-02 20:58
Actually that wouldn't help anyway since I'm 99% sure this is due to a difference in the generated rustdoc HTML. I need to build it with the original toolchain somehow.

**Comment by jyn514** [comment] 2020-09-02 21:12
I am unable to replicate the build with a toolchain that old, it errors out on `cargo metadata`.
```
2020/09/02 17:10:44 [INFO] rustwide::cmd: running `Command { std: "/home/joshua/src/rust/docs.rs-workspace/cargo-home/bin/cargo" "+1.15.0" "metadata" "--format-version" "1", kill_on_drop: false }`
Error: Building documentation failed

Caused by:
    missing field `crate_types` at line 1 column 432
```

**Comment by jyn514** [comment] 2020-09-02 21:29
Duplicate of https://github.com/rust-lang/docs.rs/issues/1005

**Closed by jyn514** 2020-09-02 21:29 UTC
Labels: A-frontend, C-bug

**Comment by jyn514** [comment] 2020-09-20 13:40
@xd009642 this has been fixed :)
