### ISSUE TITLE
Make the GitHub buttons more accessible

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/docs.rs#195] opened 2018-04-05 05:51 UTC
The link to a crate's repository is the feature I use the most; we still have space in top bar, so why not moving the button there?

**Comment by jyn514** [comment] 2021-04-17 18:54
This is a duplicate of https://github.com/rust-lang/docs.rs/issues/61.

**Closed by jyn514** 2021-04-17 18:54 UTC
