### ISSUE TITLE
Why "doesn't [my crate] have any documentation"?

### ISSUE THREAD

**Issue by alecdotninja** [rust-lang/docs.rs#505] opened 2019-12-03 02:38 UTC
I'm sorry in advance if this is a configuration issue on my end, but I'm not sure why [my crate](https://crates.io/crates/tailcall) "doesn't have any documentation".

I am able to build the docs locally with `cargo doc`:
```
$ cargo doc
 Documenting unicode-xid v0.2.0
 Documenting proc-macro2 v1.0.6
 Documenting quote v1.0.2
 Documenting syn v1.0.11
 Documenting tailcall v0.1.2 (/home/alec.larsen/Development/tailcall)
    Finished dev [unoptimized + debuginfo] target(s) in 6.86s

$ ls target/doc/tailcall/index.html
target/doc/tailcall/index.html
```

But for some reason my documentation does not appear on [docs.rs](https://docs.rs/crate/tailcall/0.1.2), and I don't see a "Builds" tab with failure information:
![screenshot](https://user-images.githubusercontent.com/4643450/70015763-ef4cc780-1543-11ea-8f1f-62efb0381663.png)

Is there somewhere else that I can look for troubleshooting steps?

**Comment by jyn514** [comment] 2019-12-03 03:03
Duplicate of #422

**Closed by jyn514** 2019-12-03 03:03 UTC
