### ISSUE TITLE
Scraping examples: works locally but not on docs.rs

### ISSUE THREAD

**Issue by killercup** [rust-lang/docs.rs#2305] opened 2023-10-13 10:12 UTC
In https://github.com/bevyengine/bevy/pull/9154, I tried adding metadata to have the many examples bevy comes with show up in their API docs.

I have a full reproduction and detailed description of what I tried here: https://github.com/killercup/test-rustdoc-example-scraping-across-workspace-on-docrs/issues/1

- - -

This relates to https://github.com/rust-lang/rust/issues/88791

cc @rust-lang/docs-rs 

(talked to @GuillaumeGomez about this already)

**Comment by GuillaumeGomez** [comment] 2023-11-08 13:17
Moved the issue in docs.rs as it seems to be a docs.rs-specific issue: every crate gets its scraped examples working when documenting them locally. My guess is that maybe we are using a read-only FS when we should not. To be confirmed.

**Comment by syphar** [comment] 2023-11-08 13:21
@GuillaumeGomez from what I remember of the discussion with @killercup , we were able to reproduce this locally, perhaps @Nemo157 knows more?

**Comment by GuillaumeGomez** [comment] 2023-11-08 13:23
That's also what I remember and yet I can't reproduce it locally again. @killercup and I talked about it in https://github.com/killercup/test-rustdoc-example-scraping-across-workspace-on-docrs/issues/1. The surprising part being that the docs.rs command line (with `cargo rustdoc`) works locally.

**Comment by Nemo157** [comment] 2023-11-08 13:39
Yeah, my recollection is that the difference was that it didn't reproduce in the repository, but only in the published package, not anything to do with what docs.rs does with that package specifically.

**Comment by GuillaumeGomez** [comment] 2023-11-08 13:42
Ok, I'll keep the issue here for the time being and try to check what's going on when we get the crate from crates.io.

**Comment by GuillaumeGomez** [comment] 2023-11-28 14:15
So more information about this (for bevy): when adding back the workspace members:

```toml
[workspace]
members = [
  "crates/*",
]
```

And copying the relevant files locally, the examples are scraped as expected. Next step is to take a look into cargo and figure out why it's even needed in the first place.

**Comment by GuillaumeGomez** [comment] 2023-11-30 18:40
Fixed in https://github.com/rust-lang/cargo/issues/13074.

**Closed by GuillaumeGomez** 2023-11-30 18:40 UTC
Labels: C-bug, T-rustdoc
