### ISSUE TITLE
Adding `rustdoc-args = ["--generate-link-to-definition"]` in `[package.metadata.docs.rs]` makes documentation coverage dissapear

### ISSUE THREAD

**Issue by carloskiki** [rust-lang/docs.rs#2581] opened 2024-08-08 02:58 UTC
Its seems that all crates that are documented with the option `rustdoc-args = ["--generate-link-to-definition"]` do not have the "documentation coverage" section in the crates' drop down menu in docs.rs.

For example: [clap](https://docs.rs/clap/latest/clap/), vs [tokio](https://docs.rs/tokio/latest/tokio/)

Why is that? Why can't there _always_ be the coverage info displayed?

**Comment by syphar** [comment] 2024-08-08 07:00
I'm not sure where the problem is here, 

my hunch would be that the rustdoc command we generate for coverage can't handle this specific arg, but I need to sift through some logs to find the actual error. 

( currently we skip over coverage and just build the docs in case of an error generating coverage)

**Comment by carloskiki** [comment] 2024-08-09 01:03
Maybe its with the `rustdoc-args` parameter as a whole, because there is the `--show-coverage` argument which you can pass to `rustdoc` to have an overview of your docs coverage printed to `stdout`. I assume this argument is used to get the coverage for docs.rs, and it overlaps with crates providing their own sets of `rustdoc-args`.

**Comment by syphar** [comment] 2024-08-13 07:08
I needed to jump though some hoops to find the actual error message. 

It is : 
> [stderr] error: --generate-link-to-definition option can only be used with HTML output format 

@GuillaumeGomez do you have an idea how to solve this best? 

in my mind, we probably need _some_ of the `rustdoc-args` for coverage, but filtering would be hard. 

Could rustdoc just _ignore_ ( and warn) ?

**Comment by GuillaumeGomez** [comment] 2024-08-13 11:46
We could indeed emit a warning and mention that the option will be ignored.

**Comment by syphar** [comment] 2024-08-13 13:19
> We could indeed emit a warning and mention that the option will be ignored.

@GuillaumeGomez that would be awesome, thanks!

**Comment by GuillaumeGomez** [comment] 2024-08-13 13:21
Already opened  rust-lang/rust#129050. :p

**Comment by syphar** [comment] 2024-08-13 15:03
I wonder if we should collect & store the coverage logs too...

**Comment by GuillaumeGomez** [comment] 2024-08-13 15:10
I mean, that would have helped here.

**Comment by GuillaumeGomez** [comment] 2024-08-14 09:29
https://github.com/rust-lang/rust/pull/129050 is now merged, so tomorrow it should be fixed on docs.rs as well. Closing then.

**Closed by GuillaumeGomez** 2024-08-14 09:29 UTC

**Comment by syphar** [comment] 2024-08-15 04:57
Just validated that the change in nightly 
- is on docs.rs 
- is working 

( I ran a rebuild for `clap`, and now we have coverage)
