### ISSUE TITLE
Feature Request: Better handling of old versions

### ISSUE THREAD

**Issue by EvanCarroll** [rust-lang/docs.rs#1411] opened 2021-05-31 02:33 UTC
It would be really nice if crates.io would not index old versions. If you're using an older version it would be great if the user had to click on the older version or search for it on crates.io. Google just always seem to prioritize older versions when I'm looking searching.

If that can't be done, it would be nice if users had an option to be redirected to the latest version of the create. Old versions are just of no use to me. If I'm reading the documentation, it's very likely that I've already updated my version to the latest.

**Comment by syphar** [comment] 2021-05-31 07:12
I don't know enough about google here. 

But: our [sitemap](https://docs.rs/sitemap.xml) only [contains URLs that redirect to the latest version](https://docs.rs/-/sitemap/a/sitemap.xml). 

From what I understand of your request is that it could be related to the discussion in #1006 (which is unsolved currently)

**Comment by EvanCarroll** [comment] 2021-06-03 04:20
Not sure, the problem is certainly google related. If I search for `warp rust reply`, I get

* https://www.google.com/search?q=warp+rust+reply

That takes you to

* https://docs.rs/warp/0.1.0/warp/reply/index.html

That's _almost_ certainly not what your users want. They're going to want 

* https://docs.rs/warp/*/warp/reply/index.html

The problem is they may not notice that until after they're a bit late in the game.

Delisting urls that don't have `/latest/` or `/*/` in their name would seem like a reasonable solution. And allow people to -- from the latest -- read the docs on earlier versions.

**Comment by syphar** [comment] 2023-01-11 20:47
I believe #1438 and the continous work of @jsha is the solution here. 

We already have much improved search results where we see the latest page when the element still exists in it. 

I'm closing this issue.

**Closed** 2023-01-11 20:47 UTC

**Comment by jsha** [comment] 2023-01-11 21:29
FWIW, I checked this specific example, and the results for "rust warp reply" on Google are currently:

1. https://docs.rs/warp/0.1.0/warp/reply/index.html
2. https://docs.rs/warp/latest/warp/reply/index.html

Not great; we want #2 to be #1, and #1 not to be listed.

I checked the Google Search Console, and Google has recently crawled both of these URLs, and sees the canonical link pointing from #1 to #2. It's just that Google is choosing to disregard the canonical link. Presumably the problem is some combination of:

 - The two pages are very different (due to the default-collapsed docblock on #1), so Google doesn't want to canonicalize one to the other.
 - #1 has a longer history of being crawled, so may be seen as more reputable.

I'm hopeful that over time, Google will establish a preference for the `/latest/` URLs, since "longer history of being crawled" will be less relevant, but at least for now this is an example where canonicalization is not doing the trick. Still, I think it's reasonable to close this issue and keep tracking progress under #1438.
