### ISSUE TITLE
falcon fails to build

### ISSUE THREAD

**Issue by endeav0r** [rust-lang/docs.rs#1351] opened 2021-04-13 21:59 UTC
Sorry, accidentally hit the create-new-issue button before I was done here. There is already an issue open for this here: https://github.com/rust-lang/docs.rs/issues/1198

**Crate name:** Falcon
**Build failure link:** https://docs.rs/crate/falcon/0.5.1/builds/375762

**Additional details:**
Falcon does not build correctly against packaged capstone4.

We have a github workflow here: https://github.com/falconre/falcon/blob/master/.github/workflows/tests.yml that successfully builds falcon. In order to do this, we download capstone, build the bindings manually, and install them.

```
          wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
          tar xf 4.0.2.tar.gz
          cd capstone-4.0.2
          make -j 8
          sudo make install
```

I'm not very familiar with the internal infrastructure of docs.rs, and understand this may be too intensive of a step for a single package. If that's the case, we'll host the docs externally. However, I'm a huge fan of docs.rs, and if we can make it work I'd love to do that.

**Comment by jyn514** [comment] 2021-04-13 22:00
This is https://github.com/rust-lang/rust/issues/84162.

**Comment by jyn514** [comment] 2021-04-14 05:37
@endeav0r we don't allow network access in the build environment. You could either avoid building capstone in the build.rs if DOCS_RS is set in the environment (https://docs.rs/about/builds#detecting-docsrs) or bundle the sources with the crates.io tarball.

**Comment by jyn514** [comment] 2021-04-15 13:24
@endeav0r I'm going to close this as a duplicate of https://github.com/rust-lang/docs.rs/issues/1198, feel free to add more info there.

**Closed by jyn514** 2021-04-15 13:24 UTC
