### ISSUE TITLE
Add `std` to search results

### ISSUE THREAD

**Issue by jjant** [rust-lang/docs.rs#2106] opened 2023-04-14 11:30 UTC
Searching `"std"` in the search bar should show the standard library but it doesn't: https://docs.rs/releases/search?query=std.

**Comment by syphar** [comment] 2023-04-16 05:16
How would you imagine this looks like? 
Currently docs.rs search is actually just calling out to the crates.io API and we return whatever the crates.io search returns. 

[Also, we have some redirects in place](https://github.com/rust-lang/docs.rs/blob/77eaf07765590a03a8dfee8da5a956f6d1792ddd/src/web/rustdoc.rs#L38-L49): 
- `docs.rs/std` redirects to https://doc.rust-lang.org/stable/std/
- `docs.rs/std::iterator` redirects to https://doc.rust-lang.org/stable/std/?search=iterator

**Comment by jyn514** [comment] 2023-05-02 03:20
Duplicate of https://github.com/rust-lang/docs.rs/issues/604

**Closed by jyn514** 2023-05-02 03:20 UTC
