### ISSUE TITLE
Incorrect "no builds" badge shown for complex version string

### ISSUE THREAD

**Issue by repi** [rust-lang/docs.rs#395] opened 2019-08-12 17:31 UTC
We have a crate that has a version string `0.1.0+4.1`, when linking to the docs.rs badge for it it shows up as "no build" when using this string: `https://docs.rs/physx-sys/badge.svg`. 

![image](https://user-images.githubusercontent.com/1262692/62884611-47628280-bd37-11e9-951c-b0700546e5ca.png)

Although the actual link works and goes to the correct built documentation for that specific crate [`https://docs.rs/physx-sys/0.1.0+4.1/physx_sys/`](https://docs.rs/physx-sys/0.1.0+4.1/physx_sys/).

Looks like there may be some specific badge picture generation error for complex version strings, maybe it tries to find version just `0.1.0`, which doesn't exist, in the picture selection instead of the full `0.1.0+4.1`. While the page link itself uses the correct one.

Cargo itself when one references a crate with such a more complex version string does only use the first semver portion (MAJOR.MINOR.PATCH) and gives a warning if one specifies the rest (which it ignores).

**Comment by arirawr** [comment] 2019-09-26 20:41
Just poking around a bit on this one - could it be related to the `+` symbol being incorrectly encoded around [here](https://github.com/rust-lang/docs.rs/blob/7ef7265012e541d1974a8ecfe9ffab7aa45d694e/src/web/mod.rs#L293-L301)?

**Comment by jyn514** [comment] 2020-01-10 13:18
Reproducible crate: https://docs.rs/zstd/0.5.1+zstd.1.4.4/zstd/

BTW @repi  the [build failure](https://docs.rs/crate/physx-sys/0.2.3+4.1.1/builds/199433) for your 2.0 versions is because cmake is trying to write to the source directory, we added more sandboxing in #407. If you write to the target directory instead (cargo sets OUT_DIR), it should work.

**Comment by jyn514** [comment] 2020-01-10 13:27
A secondary problem: if _any_ version is not a valid semver range, _all_ versions are marked as being invalid: https://github.com/rust-lang/docs.rs/blob/master/src/web/mod.rs#L267

**Comment by jyn514** [comment] 2020-01-14 00:31
@arirawr it turns out this _isn't_ a problem in `match_version`, surprisingly. Somehow, when you go to /zstd/badge.svg?version=0.5.1+zstd.1.4.4 the version that gets passed to `match_version` is `0.5.1 zstd.1.4.4` (with a space).

**Comment by jyn514** [comment] 2020-01-14 00:36
I think it might be a bug in `params`? I'm giving up for now.

**Comment by jyn514** [comment] 2020-01-14 01:03
Relevant code: https://github.com/rust-lang/docs.rs/blob/master/src/web/rustdoc.rs#L331

**Closed** 2020-04-09 17:21 UTC
