### ISSUE TITLE
In crate search for serde v1.0.125 is broken

### ISSUE THREAD

**Issue by jonasbb** [rust-lang/docs.rs#1336] opened 2021-03-27 15:38 UTC
The in crate search for serde v1.0.125 (latest) is broken. It works for v1.0.124.
I only find a search result for some `empty_library`. The only bug I could find with this term is #1313, which does not look related since serde has dependencies.

**Comment by jyn514** [comment] 2021-03-27 19:22
This is a regression from https://github.com/rust-lang/docs.rs/issues/1302, fixed by https://github.com/rust-lang/docs.rs/pull/1329. The docs are still broken because of https://github.com/rust-lang/docs.rs/issues/464, I'll rebuild serde manually.

**Comment by jyn514** [comment] 2021-03-27 19:30
Hmm, there are more regressed crates than I expected - I would rather not rebuild them all.
```
cratesfyi=> select count(*) from releases where release_time between '2021-03-21' and '2021-03-23';
count
764
(1 row)
```

**Comment by jyn514** [comment] 2021-03-27 19:39
This is fixed for serde itself, although it might not show up for a little while because of caching from our CDN.

**Closed by jyn514** 2021-03-27 19:39 UTC

**Comment by jyn514** [comment] 2021-03-27 19:46
> Hmm, there are more regressed crates than I expected - I would rather not rebuild them all.
> 
> ```
> cratesfyi=> select count(*) from releases where release_time between '2021-03-21' and '2021-03-23';
> count
> 764
> (1 row)
> ```

I queued all the latest releases instead, about 450 crates.
```sql
select name, version from releases inner join crates on crates.id = releases.crate_id where release_time between '2021-03-21' and '2021-03-23' and releases.id = crates.latest_version_id order by name;
```

**Comment by jonasbb** [comment] 2021-03-27 20:35
Thank you for rebuilding the crates.
