### ISSUE TITLE
Add GUI tests

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/docs.rs#1494] opened 2021-09-13 14:40 UTC
crates.io has GUI tests using percy: https://percy.io/crates-io/crates.io/builds/11597533/changed/652575280

We had a lot of UI regressions so it'd be nice to have a GUI testsuite to make it easier to spot them (and to know where they happen more precisely).

Things to be tested:

 * position of the footer (always at the bottom of the page)
 * icons in the topbar depending on the width of the screen
 * ...

**Comment by syphar** [comment] 2023-10-24 09:03
duplicate of #996 ( I think)

**Closed** 2023-10-24 09:03 UTC

**Comment by GuillaumeGomez** [comment] 2023-10-24 11:01
Ah inedeed. Sorry about that.
