### ISSUE TITLE
Theme: Option to prefer system UI theme in theme selector

### ISSUE THREAD

**Issue by prophet1996** [rust-lang/docs.rs#2108] opened 2023-04-16 07:03 UTC

**Comment by jyn514** [comment] 2023-05-02 03:18
Don't we already support this?
![image](https://user-images.githubusercontent.com/23638587/235572533-a698549e-c3f7-4374-876d-f73c2fd5aa07.png)

**Comment by jyn514** [comment] 2023-05-03 14:36
Ok, I'm going to close this as a duplicate of https://github.com/rust-lang/docs.rs/issues/464 then

**Closed by jyn514** 2023-05-03 14:36 UTC
