### ISSUE TITLE
Add GUI test suite

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/docs.rs#1605] opened 2022-01-16 19:52 UTC
We had a lot of UI regressions so it'd be nice to have a GUI testsuite to make it easier to spot them (and to know where they happen more precisely).

Things to be tested:

 * position of the footer (always at the bottom of the page)
 * icons in the topbar depending on the width of the screen
 * ...

**Comment by jyn514** [comment] 2022-01-16 20:07
Duplicate of https://github.com/rust-lang/docs.rs/issues/1494

**Closed by jyn514** 2022-01-16 20:07 UTC
