### ISSUE TITLE
The favicon of project docs are redirecting to http from cloudflare

### ISSUE THREAD

**Issue by abbychau** [rust-lang/docs.rs#353] opened 2019-05-12 23:46 UTC
e.g.

https://docs.rs/nom/5.0.0-beta1/nom/macro.take.html

<img width="1115" alt="Screen Shot 2019-05-13 at 8 45 10" src="https://user-images.githubusercontent.com/350283/57589186-7102e680-755b-11e9-97a7-a7c98d0e7ec6.png">

https://docs.rs/favicon-20190505-1.36.0-nightly-d628c2e64.ico
is redirecting to http://docs.rs/favicon.ico in the middle, which is not expected.

**Comment by QuietMisdreavus** [comment] 2019-05-15 19:21
Duplicate of https://github.com/rust-lang/docs.rs/issues/352

**Closed by QuietMisdreavus** 2019-05-15 19:21 UTC
