### ISSUE TITLE
firefox docs.rs not displaying correctly

### ISSUE THREAD

**Issue by Dowwie** [rust-lang/docs.rs#1669] opened 2022-02-09 16:55 UTC
I'm using a macbook pro and noticed that Firefox  isn't displaying docs.rs correctly:

page in Firefox v97.0:
![image](https://user-images.githubusercontent.com/2601236/153249684-b645d9aa-de35-4449-b4fb-6e79a6fe6c08.png)

page in Chrome:
<img width="1418" alt="Screen Shot 2022-02-09 at 11 46 05 AM" src="https://user-images.githubusercontent.com/2601236/153249989-ef3b558b-ef83-4c4d-8e75-fac61b4a4dba.png">

**Comment by Nemo157** [comment] 2022-02-09 21:30
Seems like https://github.com/rust-lang/rust/issues/93171 which should have been fixed by https://github.com/rust-lang/docs.rs/pull/1614.

**Comment by syphar** [comment] 2022-02-10 06:01
So it could be related to the minimum font-size set? 

@Dowwie what did you set? 

Perhaps it's the browser cache? ( even though the file has a hashed filename)

**Comment by GuillaumeGomez** [comment] 2022-02-10 13:58
I'd say no but for accessibility things, I don't know much so let's see what @jsha thinks.

**Comment by jsha** [comment] 2022-02-10 21:08
I think this should be fixable by setting overflow-y: hidden on the topbar
element. I avoided it before because I wanted to actually make the text
elements the right size, but it seems there are some settings that make
that hard, and overflow-y would be the reliable solution.

It would also be interesting to see why only some of the topbar items
overflow, and others (like the docs.rs title) don't.

**Comment by GuillaumeGomez** [comment] 2022-02-13 12:06
@mitsuhiko The fix was just merged: https://github.com/rust-lang/docs.rs/pull/1619. Needs to be deployed now.

**Comment by syphar** [comment] 2022-02-13 14:07
I just deployed the fix

**Comment by Dowwie** [comment] 2022-02-17 13:42
The resolved the issue that I raised.  Not sure whether to close this just yet.  @mitsuhiko Looks good on your side?

**Comment by aslpavel** [comment] 2022-03-11 21:34
It seems to be broken again

**Comment by syphar** [comment] 2022-03-12 08:00
@aslpavel it looks good on my computer, which crate & release are you looking at? Also axum/latest?

**Comment by aslpavel** [comment] 2022-03-12 11:08
- All the docs at `doc.rs` look like that
![2022-03-12T10:52:36,410102655+00:00](https://user-images.githubusercontent.com/281294/158015386-9fa9b64f-403d-478a-a5e8-d129ab0e89b0.png)

- I'm not a web developer but that looks suspicious
![2022-03-12T10:54:27,502536817+00:00](https://user-images.githubusercontent.com/281294/158015401-dc4dd12c-d950-4127-b776-b902ea970719.png)

- Removing this limit or/and setting `flex-shrink: 0` makes things better but not perfect
![2022-03-12T10:58:26,219658297+00:00](https://user-images.githubusercontent.com/281294/158015424-469feb4e-ce3a-485c-8918-3387b32db8a7.png)

- This looks identical with chromium too

- My machine is:
  - ArchLinux
  - Sway VM
  - HIDPI screen with 2x scaling 3840x2400

**Comment by GuillaumeGomez** [comment] 2022-03-12 13:11
I can't reproduce the bug on ubuntu 21.04 (firefox 98, chrome 98).

**Comment by aslpavel** [comment] 2022-03-14 21:26
If there is an additional information that I can provide to debug this, I'm happy to help

**Comment by GuillaumeGomez** [comment] 2022-03-14 22:24
Still looks good to me... Maybe the screen size is what's triggering the issue? In any case, cc @jsha

**Comment by jsha** [comment] 2022-03-15 07:19
That's quite strange indeed. I also can't reproduce on Ubuntu 21, with Firefox or Chrome (latest of both).

The thing that sticks out to me in these screenshots is that the "Releases" (and similar) menu items are missing a lower bar, as if they are just slightly too big - the same symptoms we saw previously, which we fixed by making the menu bar font sizes not responsive to the user's font size.

I wonder if it's possible this is an Arch vs Ubuntu thing? Like, could the fonts be slightly different on Arch? That would be surprising, since docs.rs brings all its own fonts.

Could you get the computed styles for the "Releases" menu heading? Here's what mine look like:

![image](https://user-images.githubusercontent.com/220205/158326159-d2610f78-9197-446b-85aa-3b5e28fc86e4.png)

Also, could you attach a screenshot of your font settings in FF?

![image](https://user-images.githubusercontent.com/220205/158326251-05134a92-9553-4fec-b8a5-5ca7b539076b.png)

![image](https://user-images.githubusercontent.com/220205/158326313-03be0194-01c3-44d4-81d4-34fb28706e24.png)

**Comment by aslpavel** [comment] 2022-03-15 13:14
I've tested everything now on my fedora machine with clean firefox profile:
- Here is requested "Release Computed Properties"
![Screenshot from 2022-03-15 13-03-00](https://user-images.githubusercontent.com/281294/158384565-744cf9de-eeaa-4a97-95f5-49cba5d8bd11.png)
- Fonts settings look identical to yours

### But I did find something that effects the results
  - looking at computed properties, first font in the list is "Fira Sans"
  -  I do have it available on the machine
```
$ fc-match "Fira Sans"
fira-sans.ttf: "Fira Sans" "Regular"
```
  - When I remove it everything renders as expected
  - I have no idea why availability of the font effects layout so drastically! Ideally font should not a effect layout at all

**Comment by GuillaumeGomez** [comment] 2022-03-15 14:04
That is very surprising indeed...

**Comment by aslpavel** [comment] 2022-03-15 19:54
Well it would be ok if I had some missing/badly rendered symbols. But this font breaks layout of the whole page.

**Comment by GuillaumeGomez** [comment] 2022-03-15 19:55
Like @jsha already wrote, we suspect a missing `overflow: hidden` in the docs.rs top bar.

**Comment by jam1garner** [comment] 2022-03-16 19:10
Copying some additional data from my comment here: https://github.com/rust-lang/rust/issues/93171#issuecomment-1069482709

* Firefox 92.0
* Ubuntu 20.04
* 1920x1080 screen, firefox **at half width** (roughly 960x1080 including window decorations), eg **vertical orientation**
* Occurs even with the font fix present

So it seems like screen size and orientation definitely plays a factor.

---

Also since this issue won't magically go away due to older crates/versions not getting CSS updates, here's some hacky client-side fixes for those who need them:

**UBlock Origin Filter**

Add under UBlock -> dashboard (the gears icon) -> "My Filters" tab

```css
docs.rs###rustdoc_body_wrapper:style(width: 100% !important;)
```

**Built-in Firefox Userstyles** (Untested, @ me if it works and I'll edit this)

```css
@-moz-document domain(docs.rs) {
    #rustdoc_body_wrapper {
        width: 100% !important;
    }
}
```
([More info on how to add](https://superuser.com/a/319322))

**Closed** 2022-04-09 16:26 UTC

**Comment by jsha** [comment] 2022-04-09 16:47
Just wanted to say thanks to all reporting and helping reproduce. Having
the old font file really helped. The fix is merged; once it's deployed it
about retroactively affect old docs (because it's docs.rs css, not rustdoc
css).
