### ISSUE TITLE
Vowpalwabbit-sys status badge shows incorrect status

### ISSUE THREAD

**Issue by jackgerrits** [rust-lang/docs.rs#612] opened 2020-02-15 14:36 UTC
**Crate name:** https://crates.io/crates/vowpalwabbit-sys
**Build failure link:** N/A

**Additional details:** 
The docs.rs build failed several times for a previous version, and I was trying to use metadata to spin new versions. (I was tracking an upstream dependency, hence my attempt to avoid incrementing the patch version)
```
8.8.0+post3 
8.8.0+post2 
8.8.0+post1
8.8.0
```

This really did not work well because they were all seen as the same version according to semver when in fact they were different. I've moved to a new versioning strategy that correctly follows semver. But it seems that the previous failed builds are still affecting the status badge:

![Badge](https://docs.rs/vowpalwabbit-sys/badge.svg?version=8.8.1+vw-v8.8.0) https://docs.rs/vowpalwabbit-sys/badge.svg?version=8.8.1+vw-v8.8.0

Would someone be able to look into why the status badge is not displaying the latest version (which built successfully)?

**Comment by jyn514** [comment] 2020-02-15 14:46
Duplicate of #395

**Closed by jyn514** 2020-02-15 14:46 UTC
Labels: build-failure

**Comment by jackgerrits** [comment] 2020-02-15 14:52
Thanks!
