### ISSUE TITLE
delete crates from database if they're deleted from crates.io

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/docs.rs#285] opened 2019-01-10 16:02 UTC
There have been a couple incidents recently where hundreds of crates were procedurally published to squat their names, and crates.io decided to delete the squatted crates after the spam attack was stopped. However, their records still exist on docs.rs, which may cause issues later on if someone else tries to register the same crate and publish the same version number. We should track crate deletions from the crates.io index and scrub the crate from our database when that happens.

This will likely need work in the `crates-index-diff` crate, since IIRC it doesn't currently check for crate deletions, just new publishes and yanks.

**Comment by jyn514** [comment] 2020-07-16 01:47
Closing as duplicate of https://github.com/rust-lang/docs.rs/issues/368

**Closed by jyn514** 2020-07-16 01:47 UTC
