### ISSUE TITLE
Static resources corresponding to 20210305-1.52.0-nightly-caca2121f are missing

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/docs.rs#1305] opened 2021-03-06 04:02 UTC
https://docs.rs/serde/1.0.123/serde/ looks fine, but https://docs.rs/serde/1.0.124/serde/ seems to fail to load a bunch of stuff.

---

![Screenshot from 2021-03-05 20-01-26](https://user-images.githubusercontent.com/1940490/110194557-a2623b80-7ded-11eb-8666-f71f27f4b1af.png)

---

![Screenshot from 2021-03-05 20-01-47](https://user-images.githubusercontent.com/1940490/110194560-a42bff00-7ded-11eb-854b-703fbb5b6e31.png)

**Comment by rkuhn** [comment] 2021-03-06 08:18
same for https://docs.rs/intern-arc/0.4.0/intern_arc/

**Comment by Nemo157** [comment] 2021-03-06 10:13
I reproduced this on my local instance:

```
copying essential files for rustc 1.52.0-nightly (caca2121f 2021-03-05)
couldn't copy '/opt/docsrs/rustwide/builds/essential-files-20210305-1.52.0-nightly-caca2121f/target/doc/FireSans-Medium.woff2' to '/tmp/essential-fileskQqkWB/FireSans-Medium.woff2'
```

But then it goes on to build the next crate in the queue and because the nightly version hasn't changed it skips acquiring the essential files.

**Comment by syphar** [comment] 2021-03-06 10:26
so it seems related to 5e5f407df272752b0427cccdf05fb7f0a04bbbff

**Comment by Nemo157** [comment] 2021-03-06 10:35
Yep, I'm not sure why though, https://github.com/rust-lang/rust/pull/82545 was merged 8 days ago so the files should be there, unless this has been reverted in the meantime?

I'm going to try making a change so that if essential files fail we don't continue building crates so that the impact of failures like this won't be so bad, but once https://github.com/rust-lang/rust/pull/82803 is merged and used this shouldn't reoccur.

**Comment by rkuhn** [comment] 2021-03-06 10:52
Thanks for quickly looking into this! However, it is not obvious to me what I need to do to get the docs fixed — please let me know.

**Comment by Nemo157** [comment] 2021-03-06 10:54
Nothing 😁, there's a bug fix we need to deploy, then we'll rebuild all affected documentation.

**Comment by rkuhn** [comment] 2021-03-06 11:03
Oh, cool! I thought I’d have to push a new version once the bug is fixed 🙂

**Comment by syphar** [comment] 2021-03-06 12:16
For this specific thing I even assume we don't even need to rebuild the docs, because they are already referencing to the correctly hashed files.

**Comment by Nemo157** [comment] 2021-03-06 13:35
Ah yes, `cratesfyi build add-essential-files` should fix it.

**Comment by jyn514** [comment] 2021-03-06 14:15
This has been fixed.

**Comment by jyn514** [comment] 2021-03-06 14:16
> Yep, I'm not sure why though, rust-lang/rust#82545 was merged 8 days ago so the files should be there, unless this has been reverted in the meantime?

We didn't try to copy the files until yesterday: https://github.com/rust-lang/docs.rs/pull/1301. Last night was the first time docs.rs tried to run a build with the new toolchain.

**Closed by jyn514** 2021-03-06 14:15 UTC
