### ISSUE TITLE
Rust doc does not fullfill the whole page on firefox with minimum font size setted

### ISSUE THREAD

**Issue by csmoe** [rust-lang/docs.rs#1706] opened 2022-03-11 06:16 UTC
![image](https://user-images.githubusercontent.com/35686186/157813654-35f599c9-95bd-4362-94bf-edd4e3f8f01e.png)

browser: Firefox 97.0.2 (64-bit) stable
Can be reproduced on macOS and Linux.

Not sure it's a firefox bug or rustdoc.

**Comment by jsha** [comment] 2022-04-07 19:26
Thanks for reporting! I believe this is a duplicate of #1669. I recommend closing in favor of that issue.

**Closed** 2022-04-08 11:14 UTC
Labels: T-rustdoc, A-rustdoc-ui
