### ISSUE TITLE
Cross-crate links do not preserve platform selected

### ISSUE THREAD

**Issue by nagisa** [rust-lang/docs.rs#96] opened 2017-01-22 16:30 UTC
Browsing the documentation for windows and clicking through to another crate results in platform being forgotten.

e.g. click Evented on [this page](https://docs.rs/tokio-core/0.1.3/x86_64-pc-windows-msvc/tokio_core/reactor/struct.PollEvented.html)

**Comment by onur** [comment] 2017-01-22 17:50
Thanks for reporting, but this is a little bit complicated.

Cross-crate links are currently using documentation URL set by crate owner.

Link of `Evented` trait is coming from mio's [`package.documentation`](https://docs.rs/crate/mio/0.6.1/source/Cargo.toml) URL. And not every crate is using docs.rs in their documentation links. I need to make a docs.rs specific rustdoc to generate 100% correctly linked documentation. I actually want to make this but I am afraid it will become so hard to maintain. rustup is making docs.rs job is a lot easier for different target platforms, and this is one of the downsides of docs.rs because of stock rustdoc.

Another example is enums: <https://docs.rs/acme-client/0.2.0/acme_client/enum.ErrorKind.html> If you check links of each type in this enum, you can see they are all using a different website originally set by crate owners.

**Comment by jyn514** [comment] 2020-03-17 23:13
Since we started passing [`--extern-html-root-url`](https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/rustwide_builder.rs#L446), we no longer read `package.documentation`, so I think this is now feasible to implement. The example given, [`ErrorKind`](https://docs.rs/acme-client/0.5.3/acme_client/error/enum.ErrorKind.html), links to all docs.rs urls in the latest version (except for `std::io::Error`).

The only concern I have is that if that for cross-crate links, the other crate might not have built the same targets as you did, resulting in a 404. I think this would be solvable by redirecting to the default target if a rustdoc page with a non-default target gives a 404.

So, the way I propose to implement this is by adding the current platform to `--extern-html-root-url`. This would only fix future builds (all existing links would still lose the platform), but shouldn't require terribly much effort from docs.rs.

**Comment by jyn514** [comment] 2021-06-21 04:27
Fixed in https://github.com/rust-lang/docs.rs/pull/1418 (I guess that means https://github.com/rust-lang/docs.rs/issues/1397 was a duplicate of this issue).

**Closed by jyn514** 2021-06-21 04:27 UTC
Labels: E-easy, P-low, mentor
