### ISSUE TITLE
docs.rs fails to build docs because ` --resource-suffix` was removed from rustc in 1.58.1

### ISSUE THREAD

**Issue by michidk** [rust-lang/docs.rs#1630] opened 2022-01-28 13:57 UTC
### Crate name

off-rs

### Build failure link

https://docs.rs/crate/off-rs/0.1.3/builds/500166

### Additional details

When pushing my crate [off-rs](https://github.com/michidk/off-rs) to crates.io the docs build fails on docs.rs with the following error:
```
[INFO] [stderr]  Documenting off-rs v0.1.3 (/opt/rustwide/workdir)
[INFO] [stderr] thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:929:16
[INFO] [stderr] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[INFO] [stderr] 
[INFO] [stderr] error: internal compiler error: unexpected panic
[INFO] [stderr] 
[INFO] [stderr] error: Unrecognized option: 'resource-suffix'
[INFO] [stderr] 
[INFO] [stderr] error: could not document `off-rs`
```

I haven't got it to work ever since it first failed (the first version worked). The repo is here: https://github.com/michidk/off-rs/tree/6a0146d4f2cadb1e46ce8849abd0269cd97d3528
Building the docs locally on my machine works without any issues, even on nightly.

I expected to see this happen: Docs build successfully on docs.rs

Instead, this happened: Rust panics, full log: https://docs.rs/crate/off-rs/0.1.3/builds/500166

Edit: Can replicated it locally, by using rustc v 1.58.1. With v1.58 it worked, with v1.58.1 it fails using this command `rustdoc +nightly --edition=2021 --crate-type lib --crate-name off_rs src/lib.rs --target x86_64-unknown-linux-gnu -o target/x86_64-unknown-linux-gnu/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=390ff25bd5d00bc9 -L dependency=target/x86_64-unknown-linux-gnu/debug/deps -L dependency=target/debug/deps -Z unstable-options --emit=invocation-specific --resource-suffix -20220126-1.60.0-nightly-6abb6385b --static-root-path / --cap-lints warn --disable-per-crate-search --crate-version 0.1.3`

Seems like `--resource-suffix` was removed from rust without adjusting docs.rs

**Comment by Nemo157** [comment] 2022-01-28 14:10
I believe the "unrecognized option" message is wrong and some side-effect of the initial error, rustdoc definitely still supports `--resource-suffix` otherwise all builds on docs.rs would be erroring. Running just `cargo doc --no-deps` complains about `--crate-version` not being supported 😅.

By just deleting the intra-doc-links it appears to be the `[`parse`](`crate::parser::Parser::parse`)` that is causing an issue; that is somehow broken on the nightly `rustdoc`.

**Comment by jyn514** [comment] 2022-01-28 14:11
--resource-suffix hasn't been removed, that's just a poor error that happens when there's an ice (being fixed in https://github.com/rust-lang/rust/pull/92310). The actual error is
```
[INFO] [stderr] thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:929:16
```

**Comment by Shemnei** [comment] 2022-01-28 14:24
Could it be the (missing) lifetime in the doc comment:
[`parse`](`crate::parser::Parser::parse`) -> [`parse`](`crate::parser::Parser::<'_>::parse`)

I thought they were not required but with the anonymous lifetime added it worked.

**Comment by Nemo157** [comment] 2022-01-28 14:26
Not sure, I tried a tiny example with a similar setup and wasn't able to reproduce, it worked just fine without a lifetime. Would be good to open a rust-lang/rust issue to try and minimize (and even if the lifetime is necessary that should be an error/warning not an ICE).

**Comment by Shemnei** [comment] 2022-01-28 14:56
Opened issue for `rust-lang/rust`: https://github.com/rust-lang/rust/issues/93428

**Closed** 2022-01-28 15:01 UTC

**Comment by Nemo157** [comment] 2022-01-31 17:48
I ran a new build since 93428 was fixed and it succeeded: <https://docs.rs/off-rs/0.1.3/off_rs/> (though, I see there's been a major version bump since so probably not that important 😁).
