### ISSUE TITLE
Question about error: Is not a library.

### ISSUE THREAD

**Issue by Corfucinas** [rust-lang/docs.rs#1380] opened 2021-04-27 09:35 UTC
**Crate name: crypto-candlesticks-rust**
**Build failure link: https://docs.rs/crate/crypto-candlesticks-rust/0.1.1/builds/382082**

I wanted to publish the same docs generated when I run the command `cargo doc --no-deps`. I'm still quite new at Rust, so I must have missed something, (yes, the package does compiles => [crate](https://crates.io/crates/crypto-candlesticks-rust)

**Comment by Nemo157** [comment] 2021-04-27 10:07
See https://github.com/rust-lang/docs.rs/issues/238, currently docs.rs does not build the documentation for binaries in a crate, only the library. This is probably the easiest case where we could start heuristically deciding to build the binary documentation, a lone binary with no library, a PR to detect and support this case might be a good way to start getting #238 implemented.

**Comment by jyn514** [comment] 2021-04-27 12:46
Duplicate of https://github.com/rust-lang/docs.rs/issues/238, see https://github.com/rust-lang/docs.rs/issues/238#issuecomment-724579558 for suggestions on how to implement this.

**Closed by jyn514** 2021-04-27 12:46 UTC
