### ISSUE TITLE
bin.doc=true and lib.doc=false documents only the lib

### ISSUE THREAD

**Issue by AE9RB** [rust-lang/docs.rs#644] opened 2020-03-17 16:20 UTC
Regarding: docs.rs/basic-lang

This crate has a lib and one bin. All of the documentation is in the bin but only the lib shows up on docs.rs.

It's doing the opposite of what I expect from my Cargo.toml:
```
[[bin]]
name = "basic"
doc = true
[lib]
name = "macros"
doc = false
```

Running cargo doc --open does what I expect.

**Comment by jyn514** [comment] 2020-03-17 17:02
In general we don't document binaries, see e.g. https://docs.rs/bat. Can I ask your use case for putting documentation in the binary instead of in the library?

**Comment by AE9RB** [comment] 2020-03-17 18:00
I used the lib for a small proc-macro I don't want to publish as a crate because there things in unstable that would let me git rid of it.

**Comment by jyn514** [comment] 2020-03-17 23:00
Closing as duplicate of https://github.com/rust-lang/docs.rs/issues/238, but I'll keep this case in mind if we ever start documenting binaries.

**Closed by jyn514** 2020-03-17 23:00 UTC

**Comment by AE9RB** [comment] 2020-03-19 16:03
I removed the proc-macro so I could use lib for docs. I didn't know that bin docs weren't published. #238 also encountered cargo doc having different behavior. Digging for docs/faq only brought me to information about setting up a dev env. I'm all set now, just wanted to explain the experience that got me here.
