### ISSUE TITLE
fixed-0.1.4 source view has line numbers and code separated

### ISSUE THREAD

**Issue by glandium** [rust-lang/docs.rs#268] opened 2018-11-30 01:02 UTC
It appears as
```
1
2
3
4
...
code line 1
code line 2
code line 3
code line 4
...
```

https://docs.rs/fixed/0.1.4/src/fixed/lib.rs.html

**Comment by pietroalbini** [comment] 2018-11-30 10:04
Duplicate of #264

**Closed by pietroalbini** 2018-11-30 10:04 UTC
