### ISSUE TITLE
Succeeded build but missing docs

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/docs.rs#449] opened 2019-10-26 17:52 UTC
**Crate name:** async-trait 0.1.17
**Build link:** https://docs.rs/crate/async-trait/0.1.17/builds/194216

**Additional details:**
The build succeeded: https://docs.rs/crate/async-trait/0.1.17/builds/194216
<p align="right"><img src="https://user-images.githubusercontent.com/1940490/67623765-04fcfd80-f7de-11e9-96cf-14cf561f529a.png" width="93%"></p>

But the docs appear as missing: https://docs.rs/crate/async-trait/0.1.17
<p align="right"><img src="https://user-images.githubusercontent.com/1940490/67623766-06c6c100-f7de-11e9-8a28-4fecb9094f65.png" width="93%"></p>

If I run `cargo doc --open` for this crate locally, I do get docs.
<p align="right"><img src="https://user-images.githubusercontent.com/1940490/67623815-894f8080-f7de-11e9-9086-2196c512f34c.png" width="93%"></p>

**Comment by glts** [comment] 2019-11-01 09:00
See #422.

**Comment by jyn514** [comment] 2019-11-26 13:35
Both these libraries are proc-macros, closing as duplicate of https://github.com/rust-lang/docs.rs/issues/422.

**Closed by jyn514** 2019-11-26 13:35 UTC
Labels: build-failure

**Comment by pietroalbini** [comment] 2019-12-09 09:37
Queued a rebuild for async-trait 0.1.21. Let me know if you want more versions to be rebuilt.

**Comment by d-e-s-o** [comment] 2019-12-10 01:00
`nitrokey-test` as well, please.

**Comment by jyn514** [comment] 2019-12-10 01:10
@d-e-s-o  just queued it: https://docs.rs/releases/queue
