### ISSUE TITLE
links (the console web browser) cannot view [src] links

### ISSUE THREAD

**Issue by 1sra3l** [rust-lang/docs.rs#1408] opened 2021-05-24 19:17 UTC
Hi,
This may be a minor edge case issue, however I find the program `links` to be far superior to other programs for RTM.
`links` does not use any JavaScript, so would it be possible to statically generate the HTML in a way that even console based web browsers (there are others) can view correctly?
Thanks in advanced.

**Comment by jyn514** [comment] 2021-05-24 19:55
Duplicate of https://github.com/rust-lang/rust/issues/84242.

**Closed by jyn514** 2021-05-24 19:55 UTC
