### ISSUE TITLE
Using build-std does not work

### ISSUE THREAD

**Issue by LunarLambda** [rust-lang/docs.rs#1722] opened 2022-04-12 15:14 UTC
### Crate name

gba

### Build failure link

https://docs.rs/crate/gba/0.5.3/builds/540808

### Additional details

The `gba` crate is meant for the `thumbv4t-none-eabi` target, meaning it requires `build-std` (and the `rust-src` component). While docs.rs hints at the ability to pass `-Z build-std` to cargo (https://docs.rs/about/metadata), this doesn't seem to actually work. Not sure if we're doing something wrong or this is simply not support currently, I could not find much documentation regarding using `build-std` on docs.rs.

Currently our only other option seems to be picking a Tier 1 or 2 target that's 'close enough' (closest would be `armv7a-none-eabi` I guess?), which seems like it could easily to other weird issues.

**Comment by jyn514** [comment] 2022-04-12 15:24
Duplicate of https://github.com/rust-lang/docs.rs/issues/1561

**Closed by jyn514** 2022-04-12 15:24 UTC
