### ISSUE TITLE
Build succeeds, yet no documentation shows up

### ISSUE THREAD

**Issue by davidpdrsn** [rust-lang/docs.rs#500] opened 2019-11-28 17:32 UTC
**Crate name:** https://crates.io/crates/bae
**Build failure link:** https://docs.rs/crate/bae/0.1.2/builds

**Additional details:**
The build succeeds, yet no documentation shows up https://docs.rs/crate/bae/0.1.2 🤔

**Comment by jyn514** [comment] 2019-11-28 17:35
Duplicate of https://github.com/rust-lang/docs.rs/issues/422

**Closed by jyn514** 2019-11-28 17:35 UTC
Labels: build-failure
