### ISSUE TITLE
"Could not resolve host: github.com"

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/docs.rs#542] opened 2019-12-30 21:34 UTC
**Crate name:** fcp_cryptoauth
**Build failure link:** https://docs.rs/crate/fcp_cryptoauth/0.3.0/builds/208947

**Additional details:** It looks like a temporary issue. Could you trigger a rebuild of the crate's doc? Thanks!

**Comment by jyn514** [comment] 2019-12-30 23:38
This is not a temporary issue, access to the network is blocked in the sandbox environment. It looks like the crate trying to access GitHub is `rust_sodium-sys`, I would recommend reaching out to them to see why they need internet access.

**Comment by ProgVal** [comment] 2019-12-31 00:23
Ok. This is apparently a known issue, I pinged them about it: https://github.com/maidsafe/rust_sodium/issues/102

**Comment by jyn514** [comment] 2019-12-31 00:33
Note that we do have `libsodium` installed in the build environment, but it's not version 1.0.17 like rust_sodium seems to require: https://github.com/maidsafe/rust_sodium#to-use-your-own-copy-of-libsodium

**Comment by jyn514** [comment] 2020-01-02 21:02
@ProgVal I'm going to close this issue since it's not a bug in docs.rs.

**Closed by jyn514** 2020-01-02 21:02 UTC
Labels: build-failure
