### ISSUE TITLE
Support to download docs offline

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang/docs.rs#83] opened 2016-11-17 08:51 UTC
I found today this site: http://devdocs.io/offline
It has support to download the documentation for offline navigation.
Would be nice if `docs.rs` would support that too.

**Comment by jyn514** [comment] 2020-02-01 16:42
Duplicate of https://github.com/rust-lang/docs.rs/issues/174

**Closed by jyn514** 2020-02-01 16:42 UTC
