### ISSUE TITLE
search for `clap` yields clap 1.5.6, even though latest version is 2.x

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/docs.rs#107] opened 2017-03-03 08:09 UTC
https://docs.rs/releases/search?query=clap

![](http://i.imgur.com/NtDOXsu.png)

https://docs.rs/clap correctly yields the latest version.

**Comment by onur** [comment] 2017-03-03 11:06
Thanks for reporting.

Looks like 1.5.6 is released after 2.20.5. Docs.rs still thinks latest released version is recent version of a crate. That was reported in #47 and I thought I fixed it but looks like I only fixed https://docs.rs/clap route.

**Comment by jyn514** [comment] 2020-05-04 02:46
Closing as duplicate of https://github.com/rust-lang/docs.rs/issues/708

(I know this issue came first but the other has more discussion)

**Closed by jyn514** 2020-05-04 02:46 UTC
