### ISSUE TITLE
rustdoc-args is ignored

### ISSUE THREAD

**Issue by Recmo** [rust-lang/docs.rs#423] opened 2019-10-07 06:42 UTC
The `zkp-stark` crate contains the following in its `Cargo.toml`:

```toml
[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", ".cargo/katex-header.html"]
```

The file `.cargo/katex-header.html` is included in the package (as can be seen [here](https://docs.rs/crate/zkp-stark/0.1.1/source/)).

Yet the generated docs do not include this header, and become unreadable: https://docs.rs/zkp-stark/0.1.1/zkp_stark/fn.prove.html

**Comment by pietroalbini** [comment] 2019-10-07 06:58
Yeah, this is a regression introduced by the recent changes. https://github.com/rust-lang/docs.rs/pull/421 should fix it.

**Comment by pietroalbini** [comment] 2019-10-07 07:21
Thanks for reporting this, the issue is now fixed! I manually rebuilt your crate and everything should work again. Are any other crates of yours affected by this so I can rebuild them?

**Closed by pietroalbini** 2019-10-07 07:21 UTC

**Comment by Recmo** [comment] 2019-10-07 09:06
That was fast! Thank you so much! I don't have others yet, but I will add Katex to a few other crates soon and bump the versions. I'm assuming that with the PR merged it should just work.

**Comment by pietroalbini** [comment] 2019-10-07 09:07
Yep, it should just work.
