### ISSUE TITLE
Docs page broken, build succeeds (1.53.0 nightly only error, 1.51.0 stable OK)

### ISSUE THREAD

**Issue by tnballo** [rust-lang/docs.rs#1390] opened 2021-05-01 16:37 UTC
Hey! I encountered a problem with generated documentation when updating a crate - believe it is a nightly bug.

### Problem, 1.53.0 nightly

Documentation for a struct's functions is completely missing:

![doc_err](https://user-images.githubusercontent.com/24994892/116788710-2432b600-aa79-11eb-951d-0e8d379ac2f7.JPG)

* [Link to `docs.rs` page demonstrating probelm](https://docs.rs/scapegoat/1.1.0/scapegoat/struct.SGMap.html)
* [Broken link to missing function `pop_first`](https://docs.rs/scapegoat/1.1.0/scapegoat/struct.SGMap.html#method.pop_first)
* [`docs.rs` build log, looks successful](https://docs.rs/crate/scapegoat/1.1.0/builds/383214)
* Tested locally, can replicate issue when using `cargo 1.53.0-nightly (0ed318d18 2021-04-23)`

### No problem, 1.51.0 stable

Docs render correctly on the stable tool chain (`cargo 1.51.0 (43b129a20 2021-03-16)`):

![docs_ok](https://user-images.githubusercontent.com/24994892/116788718-3280d200-aa79-11eb-8a8c-8ee5eac3545f.JPG)

Please let me know if I can provide more information to help root cause the issue! Thank you.

**Comment by MikailBag** [comment] 2021-05-01 16:56
Please note that the link you've posted begins to work if I expand [this](https://docs.rs/scapegoat/1.1.0/scapegoat/struct.SGMap.html#impl) implementation.

**Comment by tnballo** [comment] 2021-05-01 17:07
Thanks for pointing out that the link works post-expansion, I didn't notice this. That's good news - a more usable state.

So the functions are _not_ missing, just nested differently between the two toolchain versions it seems!

**Comment by lf-** [comment] 2021-05-11 11:03
This is better documented in #1399, which is arguably a duplicate of this one. There was a nightly released with a broken rustdoc.

**Comment by jyn514** [comment] 2021-06-12 14:41
Queued and rebuilt: https://docs.rs/scapegoat/1.1.0/scapegoat/struct.SGMap.html

**Closed by jyn514** 2021-06-12 14:41 UTC

**Comment by tnballo** [comment] 2021-06-12 15:47
Thank you @jyn514 !
