### ISSUE TITLE
Search does not complete 

### ISSUE THREAD

**Issue by hellow554** [rust-lang/docs.rs#316] opened 2019-03-13 15:19 UTC
https://docs.rs/rocket/0.4.0/rocket/?search=foobar gives me: 
![grafik](https://user-images.githubusercontent.com/921462/54290652-a3b84f00-45ab-11e9-9f75-379ddefccef4.png)

https://docs.rs/regex/1.1.2/regex/?search=foobar gives me:
![grafik](https://user-images.githubusercontent.com/921462/54290691-b599f200-45ab-11e9-88f8-f302b2caf442.png)

**Comment by QuietMisdreavus** [comment] 2019-03-19 13:58
I can't reproduce this. Can you check that all the requested resources are loading on your end? Try reloading while bypassing cache (Ctrl-F5), since this fixes some issues on the official docs site.

![image](https://user-images.githubusercontent.com/5217170/54611493-0f277400-4a25-11e9-9a0c-6b22fc756e22.png)

**Comment by hellow554** [comment] 2019-03-19 14:09
I can reproduce it (maybe you should hit ctrl+f5 ;) )

Reproduceable in Firefox, chrome and edge under windows. Even with my mobile and fennec (firefox) and mobile data.

**Comment by hellow554** [comment] 2019-03-19 14:12
![Screenshot_Fennec_F-Droid_20190319-150907](https://user-images.githubusercontent.com/921462/54612338-0ea8d080-4a59-11e9-855b-7fb6c47bb4f5.png)

**Comment by QuietMisdreavus** [comment] 2019-03-19 14:28
I wonder if it's a CDN thing... I've rebuilt the rocket docs, try reloading again. If it still doesn't work, can you check to see if you can load <https://docs.rs/rocket/0.4.0/search-index.js>? I want to make sure that you're seeing all the required files.

**Comment by hellow554** [comment] 2019-03-19 14:56
Still the same issue. Have you seen, that the console gives me an TypeError? 
```
TypeError: paths is undefined main-20190318-1.35.0-nightly-0f88167f8.js:1:29247
```

Is there a way to get a non-minified version of `main.js`?

**Comment by QuietMisdreavus** [comment] 2019-03-19 15:00
That version of `main.js` is available [on the rust-lang/rust repo](https://github.com/rust-lang/rust/blob/0f88167f89fffe321590c5148f21b7d51d44388d/src/librustdoc/html/static/main.js). Chrome can also pretty-print it in the dev tools; i don't know about Firefox.

**Comment by hellow554** [comment] 2019-03-19 15:31
Thanks for the hint with the prettification! A french person has the same issue, a US person can see it just fine. It may really be a CDN issue here? Weird.
The thing I noticed it, that there's a discrepancy between the code an the array.

Let's take these few lines of code

https://github.com/rust-lang/rust/blob/0f88167f89fffe321590c5148f21b7d51d44388d/src/librustdoc/html/static/main.js#L1556-L1562

They try to access it by `.i` and `.p` which the `rawSearchIndex[crate]` does not have, but instead it has `.items` and `.paths`. Maybe that gives you a clue?

![grafik](https://user-images.githubusercontent.com/921462/54619075-55e88e80-4a64-11e9-94de-6e875e847440.png)

**Comment by GuillaumeGomez** [comment] 2019-03-19 15:52
Nope, works fine for me. Do you add something at the end of the end to be sure users' browsers reload it when needed?

**Comment by QuietMisdreavus** [comment] 2019-03-19 15:54
We don't add the resource suffix to the search index, just to the rustdoc static files. We don't touch any of the crate-specific files. The Rocket docs have been successfully built multiple times, so it's completely possible that an older version is being cached somewhere.

**Comment by hellow554** [comment] 2019-03-19 16:03
Yep, search index gives me the "old values"

![grafik](https://user-images.githubusercontent.com/921462/54621836-b974bb00-4a68-11e9-8276-f2cf4a88f62a.png)

The header for `search-index.js` is

![grafik](https://user-images.githubusercontent.com/921462/54621943-ea54f000-4a68-11e9-9ab3-9e2da033ec39.png)

The date of december 2018 might explain a thing or two

**Comment by hellow554** [comment] 2019-03-19 16:11
Interesting enough curl gives me the correct file. My browser however doesn't.
But this is weird, because even my smartphone didn't show me the correct file and it's on mobile connection.
It *shouldn't* be a browser issue neither, because I never visited the page with edge nor chrome and I cleared the cache in firefox. What is going on here? :/

**Comment by QuietMisdreavus** [comment] 2019-03-19 16:13
I'm getting a date from last month:

![image](https://user-images.githubusercontent.com/5217170/54622578-d2b14380-4a37-11e9-9c3d-a19e96298623.png)

I'm 90% sure this is a Cloudfront thing. Docs.rs is being hosted behind Cloudfront, and i bet they're caching the search index and haven't updated it after the docs got rebuilt. The problem now is, i don't know how to tell them to update their caches, either specifically for this file or generally whenever we rebuild any previously-successful docs. :confused:

**Comment by QuietMisdreavus** [comment] 2019-03-19 16:16
(Unrelated: it's funny that this hit on Rocket's docs, because Sergio would say that you should be using [api.rocket.rs](https://api.rocket.rs/v0.4/rocket/) for hosted docs.)

**Comment by hellow554** [comment] 2019-03-19 16:17
One could do the classic trick and append a unrelated query, e.g. `search-index.js?2019-03-01` which would give me a correct file right now. :/ I never liked that

**Comment by QuietMisdreavus** [comment] 2019-03-21 19:05
Update: it looks like there's a similar issue with URLs that use a partial version number; see [this example in tokio](https://docs.rs/tokio/0.1/tokio/net/struct.TcpStream.html?search=connect). It looks like the `tokio/0.1/search-index.js` has cached the search index from a previous version of tokio, but the page is using the `main.js` from the current version, which is expecting the newer/shorter field names in the search index.

**Comment by QuietMisdreavus** [comment] 2019-04-11 19:34
cc https://github.com/rust-lang/rust/pull/59776#issuecomment-482167557

That PR suggests to start adding the resource suffix to the search index, which will sidestep the issue by making newer builds request a different URL for it. That will solve the Rocket issue, and this specific problem of `main.js` and `search-index.js` using different versions of the index structure.

However, i proposed a different solution in the linked comment: We should never serve docs on a URL that doesn't use an exact version number. Any URLs with a semver requirement instead of a version number should issue a redirect to the latest matching version. This solves the tokio issue by always requesting the newest version instead of sneakily changing `tokio/0.1/search-index.js` underneath the CDN.

However, now that i'm typing this up here, i see that that doesn't fix the Rocket problem, so maybe the complete solution is to do both this proposal and that PR. :thinking:

**Comment by galich** [comment] 2019-04-25 17:37
Seems like similar or same problem happens with tokio now:

https://docs.rs/tokio/0.1.18/tokio/ - search works
https://docs.rs/tokio/0.1.19/tokio/ - search does not work

browser console is full of

    Blocked loading mixed active content “http://docs.rs/tokio/0.1.19/tokio/”
    The script from “https://docs.rs/tokio/0.1.19/search-index-20190417-1.36.0-nightly-3c3d3c177.js” was loaded even though its MIME type (“”) is not a valid JavaScript MIME type.[Learn More]


https://github.com/tokio-rs/tokio/issues/1059

**Comment by elomatreb** [comment] 2019-04-28 09:37
Running into this on the [actix-web docs](https://docs.rs/actix-web/1.0.0-beta.2/actix_web/). This has a string in the version number (`1.0.0-beta`), maybe somethings broken with that?

**Comment by Dushistov** [comment] 2019-04-28 12:06
Looks like these happens for all recent versions of crates, see also https://internals.rust-lang.org/t/docs-rs-search-is-broken/9906 , search in previous versions of the same crate works fine.

**Comment by QuietMisdreavus** [comment] 2019-04-29 15:52
The issues with recent crates' search indexes failing to load should be fixed by https://github.com/rust-lang/docs.rs/pull/329.

**Comment by QuietMisdreavus** [comment] 2019-04-29 16:17
https://github.com/rust-lang/docs.rs/pull/329 has been deployed, recent crates should be able to complete searches now. I'll post in the internals thread about what went wrong.

**Comment by galich** [comment] 2019-04-29 16:36
it works for https://docs.rs/tokio/0.1.19/tokio/

**Comment by QuietMisdreavus** [comment] 2019-04-30 16:24
I've just opened https://github.com/rust-lang/docs.rs/pull/342 to redirect version-catchall URLs to the full version number, which should fix this issue tokio had in https://github.com/rust-lang/docs.rs/issues/316#issuecomment-475363425, and close this issue entirely.

**Closed** 2019-05-03 21:25 UTC
