### ISSUE TITLE
method links broken

### ISSUE THREAD

**Issue by 89z** [rust-lang/docs.rs#1404] opened 2021-05-14 14:31 UTC
If I go to this page:

https://docs.rs/pico-args/latest/pico_args/struct.Arguments.html

I see a method on the left called `finish`, but if I click it, it doesnt do anything:

https://docs.rs/pico-args/latest/pico_args/struct.Arguments.html#method.finish

**Comment by jyn514** [comment] 2021-06-12 14:48
I assume you meant 0.4.1, this is fixed in the latest version. This is a duplicate of https://github.com/rust-lang/docs.rs/issues/1399; I'm not going to rebuild 0.4.1 for now since the latest version works.

**Closed by jyn514** 2021-06-12 14:48 UTC
