### ISSUE TITLE
Cross-crate source links don't resolve.

### ISSUE THREAD

**Issue by bluss** [rust-lang/docs.rs#59] opened 2016-09-26 20:43 UTC
Thanks for making a great service.

Here's a tricky one:

itertools 0.5.0 reexports `either::Either` from the `either` crate. The [`either` crate](https://docs.rs/either/1) has correctly and neatly set up its doc(html_root_url) to point to its docs.rs page.

`itertools::Either` on docs.rs: https://docs.rs/itertools/0.5.0/itertools/enum.Either.html

The `[src]` link from that page is cross crate: https://docs.rs/either/1/either/enum.Either.html?gotosrc=10

And it does not resolve correctly, it ends up with redirecting to https://docs.rs/either/1/either/undefined

**Comment by onur** [comment] 2016-09-26 22:46
Thanks for reporting.

I am not sure what is causing this. This link is working fine: https://docs.rs/either/1/either/enum.Either.html

And [main.js](https://docs.rs/main-20160921-1.13.0-nightly-4f9812a59.js) is trying this:

```js
    var query = getQueryStringParams();
    if (query['gotosrc']) {
        window.location = $('#src-' + query['gotosrc']).attr('href');
    }
```

Looks like there is no link with an `id='src-10'` (there is one with `src-11`). I am not sure if this is a bug in rustdoc or docs.rs

**Comment by bluss** [comment] 2016-09-27 05:52
I see, so it was pretty close to working. If I generate docs for both crates together, it ends up using src-10 in the either crate and the link works. Probably a rustdoc bug.

On the Either.html page it generates src-11 when I build the either crate's docs in their own crate, and src-10 when I build docs as a dep of itertools.

**Comment by Kixiron** [comment] 2020-05-27 14:31
Closing as this now works as intended

**Closed by Kixiron** 2020-05-27 14:31 UTC

**Comment by jyn514** [comment] 2020-05-27 18:35
Note that the link for itertools 0.5.0 now redirects to the doc homepage for `either` which is not ideal but better than a 404. The link for the latest version of itertools works fine: https://docs.rs/itertools/0.9.0/itertools/enum.Either.html links to https://docs.rs/either/1.5.3/src/either/lib.rs.html#44-49. Still not sure if this was originally a rustdoc bug or a docs.rs bug, but it seems to be fixed now.
