### ISSUE TITLE
Cargo 0.55.0 Fails

### ISSUE THREAD

**Issue by deg4uss3r** [rust-lang/docs.rs#1470] opened 2021-08-18 22:48 UTC
### Crate name

cargo

### Build failure link

https://docs.rs/crate/cargo/0.55.0/builds/416653

### Additional details

fails locally for me as well on the same error, not sure if something in the build has changed and not been updated.

**Comment by jyn514** [comment] 2021-08-19 03:43
Duplicate of https://github.com/rust-lang/docs.rs/issues/1466

**Closed by jyn514** 2021-08-19 03:43 UTC
