### ISSUE TITLE
Generated names should sorted by  Letter-Number Sequencing

### ISSUE THREAD

**Issue by lifeforfun** [rust-lang/docs.rs#309] opened 2019-02-19 14:43 UTC
Functions/traits and other names in auto-generated docs should ordered in  Letter-Number Sequencing for fast search.
![image](https://user-images.githubusercontent.com/3098625/53023229-c4532480-3497-11e9-921a-7fef08b0cc7e.png)

**Comment by QuietMisdreavus** [comment] 2019-02-19 15:09
Duplicate of https://github.com/rust-lang/rust/issues/57448

This has been fixed upstream, but docs.rs does not rebuild docs that were built with older versions of rustdoc, so any docs that have unsorted sidebars will remain that way.

**Closed by QuietMisdreavus** 2019-02-19 15:09 UTC
