### ISSUE TITLE
Apply theme to nav bar

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/docs.rs#1042] opened 2020-09-10 03:26 UTC
It would be nice to have the nav bar apply the same theme as the documentation itself.

Current style with `ayu` theme:

![8549754a92a84d06f96b0f300fdc4bfb538c8f8c](https://user-images.githubusercontent.com/13824577/92678323-bec86400-f2f3-11ea-9395-75f8c0a981a7.png)

After proposed change:

![b169794c1313dec21100d615676b40c44a4acdaa](https://user-images.githubusercontent.com/13824577/92678344-ca1b8f80-f2f3-11ea-9e5b-168d736663cc.png)

I'd love to contribute this if that sounds good.

**Comment by jyn514** [comment] 2020-09-10 03:35
Duplicate of https://github.com/rust-lang/docs.rs/issues/918

**Closed by jyn514** 2020-09-10 03:35 UTC

**Comment by Cldfire** [comment] 2020-09-10 03:47
@andrewbanchich thank you for opening this though! I for one am very eager to see the navbar colors align with the theme, it really is an eyesore at the moment.
