### ISSUE TITLE
vendored normalize.css does strange things to html details/summary tags

### ISSUE THREAD

**Issue by pacak** [rust-lang/docs.rs#1873] opened 2022-10-06 19:36 UTC
Consider self hosted documentation, it is clear that usage examples are expandable
https://pacak.github.io/bpaf/bpaf/fn.short.html

The same function as hosted on docs.rs - it is NOT clear that they are expandable.
https://docs.rs/bpaf/0.6.1/bpaf/fn.short.html

tags in question

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

css in question is hosted here: https://docs.rs/-/static/vendored.css?0-6-0-b194f43-2022-09-25
```css
article,
aside,
details,
figcaption,
figure,
footer,
header,
hgroup,
main,
menu,
nav,
section,
summary /* <- this part */ {
 display:block
}
```

**Comment by syphar** [comment] 2022-10-09 07:10
cc @Nemo157 @GuillaumeGomez could this be rustdoc related between stable / nightly?

**Comment by Nemo157** [comment] 2022-10-10 09:59
IIRC rustdoc itself also used to override the default `summary { display }` so that docs.rs doing it didn't affect the look of the docs. Since it migrated to using `<details>` for implementing collapsing there was likely a cleanup more correctly scoping its rules so that user written `<details>` got the default styling.

I don't think we're using `<details>` anywhere, so can reset this to default.

**Comment by jsha** [comment] 2022-10-13 10:17
The linked version, https://docs.rs/bpaf/0.6.1/bpaf/fn.short.html, has missing disclosure elements.

The latest version, https://docs.rs/bpaf/latest/bpaf/fn.short.html, shows the disclosure elements. So I think 0.6.1 happened to be built on a version of rustdoc that had broken CSS for user-generated `<details>` tags.

**Comment by Nemo157** [comment] 2022-10-13 10:32
The latest version has inline styling `style="display: list-item;"` in the markdown to override what `normalize.css` applies.

**Comment by pacak** [comment] 2022-10-13 11:37
Markdown bits in question are included from https://github.com/pacak/bpaf/tree/master/src/docs and are generated by a script, in the latest version I added the inline styling so docs are not broken even with `normalize.css`.

**Comment by Nemo157** [comment] 2022-10-15 10:41
This was fixed in [normalize.css v5](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#500-october-3-2016), which is included in [pure.css v2](https://github.com/pure-css/pure/blob/master/HISTORY.md#200-2020-05-05). I've done a quick update and don't notice any style regressions so hopefully this is a trivial fix.

**Closed** 2022-10-16 19:22 UTC
