### ISSUE TITLE
https://docs.rs/std should be useable

### ISSUE THREAD

**Issue by vi** [rust-lang/docs.rs#193] opened 2018-03-30 20:50 UTC
It should either contain docs for libstd of recent-ish nightly and/or stable, or just redirect to the official location of Rust standard library docs like https://doc.rust-lang.org/std/.

`libstd` always feels like a bump in doc accessiblilty because of I need to explicitly remember about it and not use the docs.rs URL alias.

**Comment by de-vri-es** [comment] 2019-07-24 11:39
This would be very useful. I know it's my own problem, but I always forget the URL for the standard library documentation. `docs.rs` on the other hand, I always remember.

(note: I have heard about bookmarks, but I'm stubborn.)

**Comment by pietroalbini** [comment] 2019-07-24 11:40
Closing as a duplicate of https://github.com/rust-lang/docs.rs/issues/56.

**Closed by pietroalbini** 2019-07-24 11:40 UTC
