### ISSUE TITLE
docs.rs updates latest docs link before docs are built

### ISSUE THREAD

**Issue by LPGhatguy** [rust-lang/docs.rs#312] opened 2019-02-25 23:55 UTC
Hi! I just published a new version of the `rbx_reflection` crate. The previous version was `0.1.0` and the new version was `0.2.373`.

Almost immediately after publish, `https://docs.rs/rbx_reflection` started redirecting to `https://docs.rs/rbx_reflection/0.2.373/rbx_reflection/`, which was not generated yet and thus returned a 404. The docs stayed broken this way for several minutes! 😦 

Does it make sense for docs.rs to continue pointing to the old version docs until the new version is done generating? This is a crate that is going to be published automatically every couple weeks and I'd like to avoid breaking my documentation for a few minutes so often.

**Comment by onur** [comment] 2019-02-26 14:43
Docs.rs is currently adding a release information before adding documentation into database. This is definitely a bug I was aware of and will fix it as soon as we start working on new model.

**Comment by jyn514** [comment] 2020-01-18 16:21
@LPGhatguy I can't reproduce this bug, I published a crate recently but `/:crate` redirected to the latest built version instead of the latest published version. Can you try again and see if it's still an issue? If not, I'd like to close this bug.

**Comment by LPGhatguy** [comment] 2020-01-20 01:49
Sure, I'll check when I publish the next version of this crate. Could it be that the crate is very large, and that's what causes the race? One of the functions [was quite big](https://github.com/rust-lang/rust/issues/60753) when I filed this issue.

**Comment by jyn514** [comment] 2020-01-20 02:32
I double checked that the other crate was building when I refreshed the page, and 0.4 was definitely building at the same time 0.3 was displayed. I'll wait until I hear about your crate though :)

**Comment by jyn514** [comment] 2020-02-23 06:07
Closing this since I haven't been able to reproduce the bug. Feel free to reopen if this happens again.

**Closed by jyn514** 2020-02-23 06:07 UTC
