### ISSUE TITLE
sysinfo crate doesn't get its documentation generated

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/docs.rs#512] opened 2019-12-07 13:24 UTC
Linked to #511. Since it's being recognized as a binary, no documentation is generated, which is a big issue.

**Comment by jyn514** [comment] 2019-12-07 13:25
Duplicate of https://github.com/rust-lang/docs.rs/issues/511.

**Closed by jyn514** 2019-12-07 13:25 UTC
