### ISSUE TITLE
gotham_restful 0.1.0 is not available on docs.rs

### ISSUE THREAD

**Issue by msrd0** [rust-lang/docs.rs#1156] opened 2020-11-04 18:19 UTC
**Crate name:** `gotham_restful`
**Build failure link:** Not available, the build is missing

**Additional details:**

Version 0.1.0 has been published to crates.io on the 2nd October, yet docs.rs cannot find that version and claims the latest version was 0.1.0-rc0 and the latest stable was 0.0.4 (https://docs.rs/crate/gotham_restful)

**Comment by jyn514** [comment] 2020-11-04 18:27
It was in the queue with `attempt = 5`, so this is another case of https://github.com/rust-lang/docs.rs/issues/797. Checking now to see exactly what the error is.

**Comment by jyn514** [comment] 2020-11-04 18:34
[It's working now](https://docs.rs/gotham_restful/0.1.0/gotham_restful/index.html) :shrug: It will be hard to find what's going wrong here until we fix https://github.com/rust-lang/docs.rs/issues/797, so I'm going to close this as 'can't reproduce' - feel free to re-open if you're still having trouble:

**Closed by jyn514** 2020-11-04 18:34 UTC
Labels: A-builds
