### ISSUE TITLE
https://github.com/crypto-com/chain.git

### ISSUE THREAD

**Issue by ALENA1978909** [rust-lang/docs.rs#905] opened 2020-07-21 04:35 UTC
**Crate name:**
**Build failure link:**

**Requested RAM limit:**
**Requested timeout:**
**Requested number of targets:**

**Why your crate needs the resource increases:**

**Comment by Nemo157** [comment] 2020-07-21 11:24
@ALENA1978909 which specific crate from that workspace failed? Checking a crate at random (`chain-core`) it [doesn'look like it has been published to crates.io](https://crates.io/crates/chain-core).

**Comment by jyn514** [comment] 2020-07-26 22:15
I'm going to close this since it's not clear what the issue is or what crate was affected. If you're having trouble, feel free to reply with more details so we know how to help.

**Closed by jyn514** 2020-07-26 22:15 UTC
