### ISSUE TITLE
Button in dark theme has dark text

### ISSUE THREAD

**Issue by FranklinYu** [rust-lang/docs.rs#547] opened 2020-01-06 09:10 UTC
This is a styling issue of dark theme. Currently it’s:

![image](https://user-images.githubusercontent.com/3153452/71807745-d9d62c00-3020-11ea-92a5-d903a7d0348b.png)

The two buttons should be light color in dark background. Following style is recommended:

```css
#theme-choices button {
    color: #e0e0e0;
}
```

Color came from button border. I didn’t make a Pull Request because I can’t find the dark style in this repository. Recommended label: minor, easy.

**Comment by GuillaumeGomez** [comment] 2020-01-06 09:11
This is a fixed bug in rustdoc. This crate certainly has been generated some time ago with an older version.

**Comment by jyn514** [comment] 2020-01-06 12:38
Duplicate of #464

**Comment by Elinvynia** [comment] 2020-06-01 12:36
It still happened to me, with a crate that was pushed just a few minutes ago: https://docs.rs/tranquility/0.0.7/tranquility/

The crate itself was created on `2020-04-03`: https://crates.io/crates/tranquility

**Comment by GuillaumeGomez** [comment] 2020-06-01 12:49
It's weird because the rules are in rustdoc and are working fine on rustdoc side. I think this is conflict coming from docs.rs' style. Re-opening!

**Comment by Nemo157** [comment] 2020-06-01 15:34
https://github.com/rust-lang/docs.rs/blob/9bd032f0ef07b217450cee3fda4906086de9cc93/templates/style.scss#L31-L35

I think `button` can be dropped from this selector, the only `<button>` on the site ("Search" and "I'm feeling lucky") override it via other styles.

**Comment by GuillaumeGomez** [comment] 2020-06-01 15:37
I thik it's worth giving it a try. Wanna do it @Nemo157 ?

**Closed** 2020-06-04 02:23 UTC
Labels: easy
